

<script>

    document.getElementById('country').addEventListener('change', function() {
        var country = this.value;
        var statesDropdown = document.getElementById('state');

        // Clear the states dropdown
        statesDropdown.innerHTML = '<option value="0">Select State</option>';

        // Fetch states based on selected country
        var states = getStatesForCountry(country);

        // Populate the states dropdown
        states.forEach(function(state) {
            var option = document.createElement('option');
            option.value = state.code;
            option.text = state.name;
            statesDropdown.appendChild(option);
        });
    });
    document.getElementById('country').addEventListener('change', function() {
        var country = this.value;
        var statesDropdown = document.getElementById('state_modal');

        // Clear the states dropdown
        statesDropdown.innerHTML = '<option value="0">Select State</option>';

        // Fetch states based on selected country
        var states = getStatesForCountry(country);

        // Populate the states dropdown
        states.forEach(function(state) {
            var option = document.createElement('option');
            option.value = state.code;
            option.text = state.name;
            statesDropdown.appendChild(option);
        });
    });
    function getStatesForCountry(countryCode) {
        var statesData = {
            '231': [ // United States
              { code: 'AL', name: 'Alabama' },
            { code: 'AK', name: 'Alaska' },
            { code: 'AZ', name: 'Arizona' },
            { code: 'AR', name: 'Arkansas' },
            { code: 'CA', name: 'California' },
            { code: 'CO', name: 'Colorado' },
            { code: 'CT', name: 'Connecticut' },
            { code: 'DE', name: 'Delaware' },
            { code: 'FL', name: 'Florida' },
            { code: 'GA', name: 'Georgia' },
            { code: 'HI', name: 'Hawaii' },
            { code: 'ID', name: 'Idaho' },
            { code: 'IL', name: 'Illinois' },
            { code: 'IN', name: 'Indiana' },
            { code: 'IA', name: 'Iowa' },
            { code: 'KS', name: 'Kansas' },
            { code: 'KY', name: 'Kentucky' },
            { code: 'LA', name: 'Louisiana' },
            { code: 'ME', name: 'Maine' },
            { code: 'MD', name: 'Maryland' },
            { code: 'MA', name: 'Massachusetts' },
            { code: 'MI', name: 'Michigan' },
            { code: 'MN', name: 'Minnesota' },
            { code: 'MS', name: 'Mississippi' },
            { code: 'MO', name: 'Missouri' },
            { code: 'MT', name: 'Montana' },
            { code: 'NE', name: 'Nebraska' },
            { code: 'NV', name: 'Nevada' },
            { code: 'NH', name: 'New Hampshire' },
            { code: 'NJ', name: 'New Jersey' },
            { code: 'NM', name: 'New Mexico' },
            { code: 'NY', name: 'New York' },
            { code: 'NC', name: 'North Carolina' },
            { code: 'ND', name: 'North Dakota' },
            { code: 'OH', name: 'Ohio' },
            { code: 'OK', name: 'Oklahoma' },
            { code: 'OR', name: 'Oregon' },
            { code: 'PA', name: 'Pennsylvania' },
            { code: 'RI', name: 'Rhode Island' },
            { code: 'SC', name: 'South Carolina' },
            { code: 'SD', name: 'South Dakota' },
            { code: 'TN', name: 'Tennessee' },
            { code: 'TX', name: 'Texas' },
            { code: 'UT', name: 'Utah' },
            { code: 'VT', name: 'Vermont' },
            { code: 'VA', name: 'Virginia' },
            { code: 'WA', name: 'Washington' },
            { code: 'WV', name: 'West Virginia' },
            { code: 'WI', name: 'Wisconsin' },
            { code: 'WY', name: 'Wyoming' },
                // Add more states
            ],
            '230': [
        // England
        { code: 'ENG', name: 'England' },
        { code: 'BIR', name: 'Birmingham' },
        { code: 'LDS', name: 'Leeds' },
        { code: 'LIV', name: 'Liverpool' },
        { code: 'MAN', name: 'Manchester' },
        { code: 'LON', name: 'London' },
        { code: 'NCL', name: 'Newcastle upon Tyne' },
        { code: 'NTS', name: 'Nottingham' },
        { code: 'SHE', name: 'Sheffield' },

        // Scotland
        { code: 'SCT', name: 'Scotland' },
        { code: 'ABD', name: 'Aberdeen' },
        { code: 'DND', name: 'Dundee' },
        { code: 'EDN', name: 'Edinburgh' },
        { code: 'GLA', name: 'Glasgow' },

        // Wales
        { code: 'WLS', name: 'Wales' },
        { code: 'CAR', name: 'Cardiff' },
        { code: 'SWA', name: 'Swansea' },

        // Northern Ireland
        { code: 'NIR', name: 'Northern Ireland' },
        { code: 'BFS', name: 'Belfast' },
        { code: 'DER', name: 'Derry' },
        { code: 'LIS', name: 'Lisburn' },
    ],
            '101': [ // India
            { code: 'AP', name: 'Andhra Pradesh' },
            { code: 'AR', name: 'Arunachal Pradesh' },
            { code: 'AS', name: 'Assam' },
            { code: 'BR', name: 'Bihar' },
            { code: 'CT', name: 'Chhattisgarh' },
            { code: 'GA', name: 'Goa' },
            { code: 'GJ', name: 'Gujarat' },
            { code: 'HR', name: 'Haryana' },
            { code: 'HP', name: 'Himachal Pradesh' },
            { code: 'JK', name: 'Jammu & Kashmir' },
            { code: 'JH', name: 'Jharkhand' },
            { code: 'KA', name: 'Karnataka' },
            { code: 'KL', name: 'Kerala' },
            { code: 'MP', name: 'Madhya Pradesh' },
            { code: 'MH', name: 'Maharashtra' },
            { code: 'MN', name: 'Manipur' },
            { code: 'ML', name: 'Meghalaya' },
            { code: 'MZ', name: 'Mizoram' },
            { code: 'NL', name: 'Nagaland' },
            { code: 'OR', name: 'Odisha' },
            { code: 'PB', name: 'Punjab' },
            { code: 'RJ', name: 'Rajasthan' },
            { code: 'SK', name: 'Sikkim' },
            { code: 'TN', name: 'Tamil Nadu' },
            { code: 'TS', name: 'Telangana' },
            { code: 'TR', name: 'Tripura' },
            { code: 'UP', name: 'Uttar Pradesh' },
            { code: 'UK', name: 'Uttarakhand' },
            { code: 'WB', name: 'West Bengal' },
            { code: 'AN', name: 'Andaman and Nicobar Islands' },
            { code: 'CH', name: 'Chandigarh' },
            { code: 'DN', name: 'Dadra and Nagar Haveli and Daman and Diu' },
            { code: 'DL', name: 'Delhi' },
            { code: 'LD', name: 'Lakshadweep' },
            { code: 'PY', name: 'Puducherry' },
        ],

        '142': [ // Mexico
            { code: 'AGU', name: 'Aguascalientes' },
            { code: 'BCN', name: 'Baja California' },
            { code: 'BCS', name: 'Baja California Sur' },
            { code: 'CAM', name: 'Campeche' },
            { code: 'CHP', name: 'Chiapas' },
            { code: 'CHH', name: 'Chihuahua' },
            { code: 'COA', name: 'Coahuila' },
            { code: 'COL', name: 'Colima' },
            { code: 'DUR', name: 'Durango' },
            { code: 'GUA', name: 'Guanajuato' },
            { code: 'GRO', name: 'Guerrero' },
            { code: 'HID', name: 'Hidalgo' },
            { code: 'JAL', name: 'Jalisco' },
            { code: 'MEX', name: 'México' },
            { code: 'MIC', name: 'Michoacán' },
            { code: 'MOR', name: 'Morelos' },
            { code: 'NAY', name: 'Nayarit' },
            { code: 'NLE', name: 'Nuevo León' },
            { code: 'OAX', name: 'Oaxaca' },
            { code: 'PUE', name: 'Puebla' },
            { code: 'QUE', name: 'Querétaro' },
            { code: 'ROO', name: 'Quintana Roo' },
            { code: 'SLP', name: 'San Luis Potosí' },
            { code: 'SIN', name: 'Sinaloa' },
            { code: 'SON', name: 'Sonora' },
            { code: 'TAB', name: 'Tabasco' },
            { code: 'TAM', name: 'Tamaulipas' },
            { code: 'TLA', name: 'Tlaxcala' },
            { code: 'VER', name: 'Veracruz' },
            { code: 'YUC', name: 'Yucatán' },
            { code: 'ZAC', name: 'Zacatecas' },
        ],
        '82': [ // Germany
            { code: 'BW', name: 'Baden-Württemberg' },
            { code: 'BY', name: 'Bavaria (Bayern)' },
            { code: 'BE', name: 'Berlin' },
            { code: 'BB', name: 'Brandenburg' },
            { code: 'HB', name: 'Bremen' },
            { code: 'HH', name: 'Hamburg' },
            { code: 'HE', name: 'Hesse (Hessen)' },
            { code: 'MV', name: 'Mecklenburg-Vorpommern' },
            { code: 'NI', name: 'Lower Saxony (Niedersachsen)' },
            { code: 'NW', name: 'North Rhine-Westphalia (Nordrhein-Westfalen)' },
            { code: 'RP', name: 'Rhineland-Palatinate (Rheinland-Pfalz)' },
            { code: 'SL', name: 'Saarland' },
            { code: 'SN', name: 'Saxony (Sachsen)' },
            { code: 'ST', name: 'Saxony-Anhalt (Sachsen-Anhalt)' },
            { code: 'SH', name: 'Schleswig-Holstein' },
            { code: 'TH', name: 'Thuringia (Thüringen)' },
        ],
        '2': [ // Albania
        { code: 'AL-01', name: 'Berat' },
        { code: 'AL-02', name: 'Dibër' },
        { code: 'AL-03', name: 'Durrës' },
        { code: 'AL-04', name: 'Elbasan' },
        { code: 'AL-05', name: 'Shkodër' },
        { code: 'AL-06', name: 'Korçë' },
        { code: 'AL-07', name: 'Fier' },
        { code: 'AL-08', name: 'Tiranë' },
        { code: 'AL-09', name: 'Vlorë' },
        { code: 'AL-10', name: 'Gjirokastër' },
        { code: 'AL-11', name: 'Kukës' },
        { code: 'AL-12', name: 'Shijak' }
    ],'10': [ // Argentina
        { code: 'AR-01', name: 'Buenos Aires' },
        { code: 'AR-02', name: 'Catamarca' },
        { code: 'AR-03', name: 'Chaco' },
        { code: 'AR-04', name: 'Chubut' },
        { code: 'AR-05', name: 'Córdoba' },
        { code: 'AR-06', name: 'Corrientes' },
        { code: 'AR-07', name: 'Entre Ríos' },
        { code: 'AR-08', name: 'Formosa' },
        { code: 'AR-09', name: 'Jujuy' },
        { code: 'AR-10', name: 'La Pampa' },
        { code: 'AR-11', name: 'La Rioja' },
        { code: 'AR-12', name: 'Mendoza' },
        { code: 'AR-13', name: 'Misiones' },
        { code: 'AR-14', name: 'Neuquén' },
        { code: 'AR-15', name: 'Río Negro' },
        { code: 'AR-16', name: 'Salta' },
        { code: 'AR-17', name: 'San Juan' },
        { code: 'AR-18', name: 'San Luis' },
        { code: 'AR-19', name: 'Santa Cruz' },
        { code: 'AR-20', name: 'Santa Fe' },
        { code: 'AR-21', name: 'Santiago del Estero' },
        { code: 'AR-22', name: 'Tierra del Fuego' },
        { code: 'AR-23', name: 'Tucumán' }
    ],
    '30': [ // Brazil
        { code: 'BR-AC', name: 'Acre' },
        { code: 'BR-AL', name: 'Alagoas' },
        { code: 'BR-AP', name: 'Amapá' },
        { code: 'BR-AM', name: 'Amazonas' },
        { code: 'BR-BA', name: 'Bahia' },
        { code: 'BR-CE', name: 'Ceará' },
        { code: 'BR-DF', name: 'Distrito Federal' },
        { code: 'BR-ES', name: 'Espírito Santo' },
        { code: 'BR-GO', name: 'Goiás' },
        { code: 'BR-MA', name: 'Maranhão' },
        { code: 'BR-MT', name: 'Mato Grosso' },
        { code: 'BR-MS', name: 'Mato Grosso do Sul' },
        { code: 'BR-MG', name: 'Minas Gerais' },
        { code: 'BR-PA', name: 'Pará' },
        { code: 'BR-PB', name: 'Paraíba' },
        { code: 'BR-PR', name: 'Paraná' },
        { code: 'BR-PE', name: 'Pernambuco' },
        { code: 'BR-PI', name: 'Piauí' },
        { code: 'BR-RJ', name: 'Rio de Janeiro' },
        { code: 'BR-RN', name: 'Rio Grande do Norte' },
        { code: 'BR-RS', name: 'Rio Grande do Sul' },
        { code: 'BR-RO', name: 'Rondônia' },
        { code: 'BR-RR', name: 'Roraima' },
        { code: 'BR-SC', name: 'Santa Catarina' },
        { code: 'BR-SP', name: 'São Paulo' },
        { code: 'BR-SE', name: 'Sergipe' },
        { code: 'BR-TO', name: 'Tocantins' }
    ],
    '21': [ // Belgium
        { code: 'BE-BRU', name: 'Brussels-Capital Region' },
        { code: 'BE-VAN', name: 'Flanders' },
        { code: 'BE-WAL', name: 'Wallonia' }
    ],
    '22': [ // Belize
        { code: 'BZ-CY', name: 'Cayo' },
        { code: 'BZ-CZ', name: 'Corozal' },
        { code: 'BZ-BZ', name: 'Belize' },
        { code: 'BZ-SC', name: 'Stann Creek' },
        { code: 'BZ-TG', name: 'Toledo' },
        { code: 'BZ-BZ', name: 'Belize District' }
    ],
    '304': [ // Botswana
        { code: 'BW-CE', name: 'Central' },
        { code: 'BW-GH', name: 'Ghanzi' },
        { code: 'BW-KW', name: 'Kweneng' },
        { code: 'BW-NW', name: 'North-West' },
        { code: 'BW-NE', name: 'North-East' },
        { code: 'BW-SH', name: 'Southern' },
        { code: 'BW-SO', name: 'South-East' },
        { code: 'BW-WE', name: 'Western' }
    ],
    '38': [ // Canada
        { code: 'CA-AB', name: 'Alberta' },
        { code: 'CA-BC', name: 'British Columbia' },
        { code: 'CA-MB', name: 'Manitoba' },
        { code: 'CA-NB', name: 'New Brunswick' },
        { code: 'CA-NL', name: 'Newfoundland and Labrador' },
        { code: 'CA-NS', name: 'Nova Scotia' },
        { code: 'CA-ON', name: 'Ontario' },
        { code: 'CA-PE', name: 'Prince Edward Island' },
        { code: 'CA-QC', name: 'Quebec' },
        { code: 'CA-SK', name: 'Saskatchewan' },
        { code: 'CA-NT', name: 'Northwest Territories' },
        { code: 'CA-NU', name: 'Nunavut' },
        { code: 'CA-YT', name: 'Yukon' }
    ],
    '40': [ // Cayman Islands
        { code: 'KY-01', name: 'George Town' },
        { code: 'KY-02', name: 'West Bay' },
        { code: 'KY-03', name: 'Bodden Town' },
        { code: 'KY-04', name: 'North Side' },
        { code: 'KY-05', name: 'East End' }
    ],
    '43': [ // Chile
        { code: 'CL-AI', name: 'Aysén del General Carlos Ibáñez del Campo' },
        { code: 'CL-AN', name: 'Antofagasta' },
        { code: 'CL-AR', name: 'Araucanía' },
        { code: 'CL-BA', name: 'Bío-Bío' },
        { code: 'CL-CO', name: 'Coquimbo' },
        { code: 'CL-LI', name: 'Libertador General Bernardo O\'Higgins' },
        { code: 'CL-LA', name: 'Los Lagos' },
        { code: 'CL-MA', name: 'Magallanes y de la Antártica Chilena' },
        { code: 'CL-MO', name: 'Maule' },
        { code: 'CL-NB', name: 'Ñuble' },
        { code: 'CL-RM', name: 'Región Metropolitana de Santiago' },
        { code: 'CL-TA', name: 'Tarapacá' },
        { code: 'CL-VE', name: 'Valparaíso' }
    ],
    '3': [ // Algeria
        { code: 'DZ-01', name: 'Adrar' },
        { code: 'DZ-02', name: 'Chlef' },
        { code: 'DZ-03', name: 'Laghouat' },
        { code: 'DZ-04', name: 'Oum El Bouaghi' },
        { code: 'DZ-05', name: 'Batna' },
        { code: 'DZ-06', name: 'Béjaïa' },
        { code: 'DZ-07', name: 'Biskra' },
        { code: 'DZ-08', name: 'Bordj Bou Arréridj' },
        { code: 'DZ-09', name: 'Bouira' },
        { code: 'DZ-10', name: 'Tamanrasset' },
        { code: 'DZ-11', name: 'Tébessa' },
        { code: 'DZ-12', name: 'Tiaret' },
        { code: 'DZ-13', name: 'Tizi Ouzou' },
        { code: 'DZ-14', name: 'Alger' },
        { code: 'DZ-15', name: 'Djelfa' },
        { code: 'DZ-16', name: 'Jijel' },
        { code: 'DZ-17', name: 'Sétif' },
        { code: 'DZ-18', name: 'Saïda' },
        { code: 'DZ-19', name: 'Skikda' },
        { code: 'DZ-20', name: 'Sidi Bel Abbès' },
        { code: 'DZ-21', name: 'Annaba' },
        { code: 'DZ-22', name: 'Guelma' },
        { code: 'DZ-23', name: 'Constantine' },
        { code: 'DZ-24', name: 'Médéa' },
        { code: 'DZ-25', name: 'Mostaganem' },
        { code: 'DZ-26', name: 'MSila' },
        { code: 'DZ-27', name: 'Naama' },
        { code: 'DZ-28', name: 'Aïn Témouchent' },
        { code: 'DZ-29', name: 'Ghardaïa' },
        { code: 'DZ-30', name: 'Relizane' }
    ],
    '5': [ // Andorra
        { code: 'AD-02', name: 'Andorra la Vella' },
        { code: 'AD-03', name: 'Escaldes-Engordany' },
        { code: 'AD-04', name: 'Encamp' },
        { code: 'AD-05', name: 'Canillo' },
        { code: 'AD-06', name: 'La Massana' },
        { code: 'AD-07', name: 'Sant Julià de Lòria' },
        { code: 'AD-08', name: 'Les Escaldes' },
        { code: 'AD-09', name: 'Ordino' },
        { code: 'AD-10', name: 'Sant Bartomeu' },
        { code: 'AD-11', name: 'Sant Joan de Caselles' },
    ],
    '302': [ // Angola
        { code: 'BGO', name: 'Benguela' },
        { code: 'CNN', name: 'Cuanza Norte' },
        { code: 'CUA', name: 'Cuanza Sul' },
        { code: 'HUA', name: 'Huambo' },
        { code: 'HUI', name: 'Huíla' },
        { code: 'LUA', name: 'Luanda' },
        { code: 'LNO', name: 'Lunda Norte' },
        { code: 'LSU', name: 'Lunda Sul' },
        { code: 'MAL', name: 'Malanje' },
        { code: 'NAM', name: 'Namibe' },
        { code: 'UIG', name: 'Uíge' },
        { code: 'ZAI', name: 'Zaire' }
    ],
    '7': [ // Anguilla
        { code: 'ANG', name: 'Anguilla' }
    ],
    '9': [ // Antigua and Barbuda
        { code: 'AN', name: 'Antigua' },
        { code: 'BA', name: 'Barbuda' },
        { code: 'SM', name: 'Saint Mary' },
        { code: 'ST', name: 'Saint John' },
        { code: 'SG', name: 'Saint George' },
        { code: 'SI', name: 'Saint Paul' },
        { code: 'SN', name: 'Saint Philip' },
        { code: 'SO', name: 'Saint Peter' },
        { code: 'SB', name: 'Saint Barthélemy' }, // If considering smaller islands
        { code: 'MD', name: 'Montserrat' } // If considering nearby territories
    ],
    '12': [ // Aruba
        { code: 'A', name: 'Aruba' }, // The whole island is often considered as one region
        { code: 'NO', name: 'Noord' },
        { code: 'OR', name: 'Oranjestad' },
        { code: 'S', name: 'San Nicolas' },
        { code: 'M', name: 'Malmok' },
        { code: 'SAB', name: 'Savaneta' },
        { code: 'D', name: 'Druif' }
    ],
    '13': [ // Australia
        { code: 'ACT', name: 'Australian Capital Territory' },
        { code: 'NSW', name: 'New South Wales' },
        { code: 'NT', name: 'Northern Territory' },
        { code: 'QLD', name: 'Queensland' },
        { code: 'SA', name: 'South Australia' },
        { code: 'TAS', name: 'Tasmania' },
        { code: 'VIC', name: 'Victoria' },
        { code: 'WA', name: 'Western Australia' }
    ],
    '14': [ // Austria
        { code: 'Burgenland', name: 'Burgenland' },
        { code: 'Carinthia', name: 'Carinthia' },
        { code: 'Lower Austria', name: 'Lower Austria' },
        { code: 'Upper Austria', name: 'Upper Austria' },
        { code: 'Salzburg', name: 'Salzburg' },
        { code: 'Styria', name: 'Styria' },
        { code: 'Tyrol', name: 'Tyrol' },
        { code: 'Vorarlberg', name: 'Vorarlberg' },
        { code: 'Vienna', name: 'Vienna' }
    ],

    '15': [ // Azerbaijan
        { code: 'BA', name: 'Baku' },
        { code: 'GA', name: 'Ganja' },
        { code: 'LAC', name: 'Lankaran' },
        { code: 'SM', name: 'Sumqayit' },
        { code: 'SH', name: 'Shirvan' },
        { code: 'NW', name: 'Nakhchivan' }
    ],
    '16': [ // Bahamas
        { code: 'AC', name: 'Acklins' },
        { code: 'BC', name: 'Berry Islands' },
        { code: 'BI', name: 'Bimini' },
        { code: 'BK', name: 'Black Point' },
        { code: 'CE', name: 'Cat Island' },
        { code: 'CS', name: 'Central Andros' },
        { code: 'EX', name: 'Exuma' },
        { code: 'GB', name: 'Grand Bahama' },
        { code: 'HI', name: 'Harbour Island' },
        { code: 'LI', name: 'Long Island' },
        { code: 'NC', name: 'New Providence' },
        { code: 'RI', name: 'Ragged Island' },
        { code: 'SB', name: 'San Salvador' },
        { code: 'SP', name: 'Spanish Wells' }
    ],
    '19': [ // Barbados
        { code: 'CH', name: 'Christ Church' },
        { code: 'ST', name: 'Saint Andrew' },
        { code: 'SM', name: 'Saint Michael' },
        { code: 'SG', name: 'Saint George' },
        { code: 'SL', name: 'Saint Lucy' },
        { code: 'SM', name: 'Saint James' },
        { code: 'SB', name: 'Saint Barnabas' },
        { code: 'SN', name: 'Saint Nicholas' },
        { code: 'ST', name: 'Saint Thomas' },
        { code: 'SS', name: 'Saint Joseph' },
        { code: 'SW', name: 'Saint Philip' },
        { code: 'SV', name: 'Saint Vincent' }
    ],
    '20': [ // Belarus
        { code: 'BR', name: 'Brest Region' },
        { code: 'HO', name: 'Grodno Region' },
        { code: 'HM', name: 'Homyel Region' },
        { code: 'MI', name: 'Minsk Region' },
        { code: 'MA', name: 'Mogilev Region' },
        { code: 'VI', name: 'Vitebsk Region' },
        { code: 'MN', name: 'Minsk City' }
    ],
    '303': [ // Benin
        { code: 'AL', name: 'Alibori' },
        { code: 'AT', name: 'Atakora' },
        { code: 'BO', name: 'Borgou' },
        { code: 'DAS', name: 'Donga' },
        { code: 'KO', name: 'Kouffo' },
        { code: 'LITT', name: 'Littoral' },
        { code: 'MON', name: 'Mono' },
        { code: 'OU', name: 'Oueme' },
        { code: 'PL', name: 'Plateau' },
        { code: 'ZE', name: 'Zou' }
    ],
    '24': [ // Bermuda
        { code: 'H', name: 'Hamilton' },
        { code: 'K', name: 'St. George\'s' },
        { code: 'S', name: 'Somerset' }
    ],
    '26': [ // Bolivia
        { code: 'B', name: 'Beni' },
        { code: 'C', name: 'Cochabamba' },
        { code: 'CH', name: 'Chuquisaca' },
        { code: 'LP', name: 'La Paz' },
        { code: 'OR', name: 'Oruro' },
        { code: 'PN', name: 'Pando' },
        { code: 'PT', name: 'Potosí' },
        { code: 'SC', name: 'Santa Cruz' },
        { code: 'SD', name: 'Tarija' }
    ],
    '27': [ // Bosnia & Herzegovina
        { code: 'BA', name: 'Federation of Bosnia and Herzegovina' },
        { code: 'RS', name: 'Republika Srpska' },
        { code: 'BR', name: 'Brčko District' }
    ],
    '304': [ // Botswana
        { code: 'CE', name: 'Central' },
        { code: 'GH', name: 'Ghanzi' },
        { code: 'KW', name: 'Kweneng' },
        { code: 'NG', name: 'Ngamiland' },
        { code: 'NW', name: 'North-West' },
        { code: 'SO', name: 'Southern' }
    ],
    
    '33': [ // Bulgaria
        { code: '01', name: 'Blagoevgrad' },
        { code: '02', name: 'Burgas' },
        { code: '03', name: 'Dobrich' },
        { code: '04', name: 'Gabrovo' },
        { code: '05', name: 'Kardzhali' },
        { code: '06', name: 'Kyustendil' },
        { code: '07', name: 'Lovech' },
        { code: '08', name: 'Montana' },
        { code: '09', name: 'Pazardzhik' },
        { code: '10', name: 'Pernik' },
        { code: '11', name: 'Plovdiv' },
        { code: '12', name: 'Ruse' },
        { code: '13', name: 'Shumen' },
        { code: '14', name: 'Sofia City' },
        { code: '15', name: 'Sofia Province' },
        { code: '16', name: 'Varna' },
        { code: '17', name: 'Veliko Tarnovo' },
        { code: '18', name: 'Vidin' },
        { code: '19', name: 'Vratsa' },
        { code: '20', name: 'Yambol' }
    ],
    '305': [ // Burkina Faso
        { code: 'BL', name: 'Boucle du Mouhoun' },
        { code: 'CE', name: 'Centre' },
        { code: 'CO', name: 'Centre-Ouest' },
        { code: 'NE', name: 'Centre-Est' },
        { code: 'NO', name: 'Nord' },
        { code: 'PL', name: 'Plateau-Central' },
        { code: 'SD', name: 'Sud-Ouest' },
        { code: 'SE', name: 'Sud' },
        { code: 'EST', name: 'Est' }
    ],
    '306': [ // Burundi
        { code: 'BU', name: 'Bujumbura' },
        { code: 'GIT', name: 'Gitega' },
        { code: 'KIR', name: 'Kirundo' },
        { code: 'MAK', name: 'Makamba' },
        { code: 'MUR', name: 'Muramvya' },
        { code: 'MW', name: 'Mwaro' },
        { code: 'NG', name: 'Ngozi' },
        { code: 'RU', name: 'Rumonge' },
        { code: 'RUT', name: 'Rutana' },
        { code: 'TA', name: 'Tavane' }
    ],
    '307': [ // Cabo Verde
        { code: 'BR', name: 'Brava' },
        { code: 'CA', name: 'Cabo Verde' },
        { code: 'FA', name: 'Fogo' },
        { code: 'MA', name: 'Maio' },
        { code: 'SA', name: 'Sal' },
        { code: 'SV', name: 'Santiago' },
        { code: 'SO', name: 'São Nicolau' },
        { code: 'TA', name: 'Tarrafal' }
    ],
    '308': [ // Cameroon
        { code: 'AD', name: 'Adamaoua' },
        { code: 'CE', name: 'Centre' },
        { code: 'ES', name: 'East' },
        { code: 'LN', name: 'Littoral' },
        { code: 'NO', name: 'North' },
        { code: 'NW', name: 'North-West' },
        { code: 'OU', name: 'South' },
        { code: 'SW', name: 'South-West' },
        { code: 'WH', name: 'West' }
    ],
    
    '154': [ // Caribbean Netherlands
        { code: 'BES', name: 'Bonaire' },
        { code: 'BES', name: 'Sint Eustatius' },
        { code: 'BES', name: 'Saba' }
    ],
    '304': [ // Botswana
        { code: 'CE', name: 'Central' },
        { code: 'GH', name: 'Ghanzi' },
        { code: 'KW', name: 'Kweneng' },
        { code: 'NG', name: 'Ngamiland' },
        { code: 'NW', name: 'North-West' },
        { code: 'SO', name: 'Southern' }
    ],
    '309': [ // Central African Republic
        { code: 'BM', name: 'Bamingui-Bangoran' },
        { code: 'BK', name: 'Basse-Kotto' },
        { code: 'HK', name: 'Haute-Kotto' },
        { code: 'HMP', name: 'Haut-Mbomou' },
        { code: 'KEM', name: 'Kemo' },
        { code: 'LB', name: 'Lobaye' },
        { code: 'MB', name: 'Mbomou' },
        { code: 'MP', name: 'Mambere-Kadei' },
        { code: 'NM', name: 'Nana-Mambere' },
        { code: 'OM', name: 'Ouham' },
        { code: 'OMB', name: 'Ouham-Pende' },
        { code: 'SAN', name: 'Sangha-Mbaere' },
        { code: 'SE', name: 'Semo' },
        { code: 'UA', name: 'Uele' }
    ],
    '312': [ // Chad
        { code: 'BA', name: 'Bahr El Gazel' },
        { code: 'BO', name: 'Borkou' },
        { code: 'CA', name: 'Chad' },
        { code: 'CO', name: 'Logone Occidental' },
        { code: 'EA', name: 'Ennedi' },
        { code: 'HA', name: 'Hadjer-Lamis' },
        { code: 'KC', name: 'Kanem' },
        { code: 'LI', name: 'Littoral' },
        { code: 'MO', name: 'Mandoul' },
        { code: 'ME', name: 'Middle Chari' },
        { code: 'NE', name: 'NDjamena' },
        { code: 'OC', name: 'Ouaddaï' },
        { code: 'SG', name: 'Sila' },
        { code: 'TA', name: 'Tandjilé' },
        { code: 'TI', name: 'Tibesti' },
        { code: 'WO', name: 'Wadi Fira' }
    ],
    '300': [ // China
        { code: 'BJ', name: 'Beijing' },
        { code: 'TJ', name: 'Tianjin' },
        { code: 'SH', name: 'Shanghai' },
        { code: 'CQ', name: 'Chongqing' },
        { code: 'GD', name: 'Guangdong' },
        { code: 'JS', name: 'Jiangsu' },
        { code: 'ZJ', name: 'Zhejiang' },
        { code: 'SC', name: 'Sichuan' },
        { code: 'HB', name: 'Hubei' },
        { code: 'HL', name: 'Heilongjiang' },
        { code: 'SX', name: 'Shanxi' },
        { code: 'LN', name: 'Liaoning' },
        { code: 'SHX', name: 'Shaanxi' },
        { code: 'YN', name: 'Yunnan' },
        { code: 'GX', name: 'Guangxi' },
        { code: 'XJ', name: 'Xinjiang' },
        { code: 'NX', name: 'Ningxia' },
        { code: 'QH', name: 'Qinghai' },
        { code: 'GZ', name: 'Guizhou' },
        { code: 'JSU', name: 'Jilin' }
    ],
    '236': [ // Vatican City
        { code: 'VA', name: 'Vatican City' }
    ],
    '47': [ // Colombia
        { code: 'AMA', name: 'Amazonas' },
        { code: 'ANT', name: 'Antioquia' },
        { code: 'ARA', name: 'Arauca' },
        { code: 'ATL', name: 'Atlántico' },
        { code: 'BOL', name: 'Bolívar' },
        { code: 'BOY', name: 'Boyacá' },
        { code: 'CAL', name: 'Caldas' },
        { code: 'CAQ', name: 'Caquetá' },
        { code: 'CAS', name: 'Casanare' },
        { code: 'CER', name: 'Cesar' },
        { code: 'CHO', name: 'Chocó' },
        { code: 'CUN', name: 'Cundinamarca' },
        { code: 'HUI', name: 'Huila' },
        { code: 'MAG', name: 'Magdalena' },
        { code: 'META', name: 'Meta' },
        { code: 'NAR', name: 'Nariño' },
        { code: 'NDS', name: 'Norte de Santander' },
        { code: 'PUT', name: 'Putumayo' },
        { code: 'QUI', name: 'Quindío' },
        { code: 'RIS', name: 'Risaralda' },
        { code: 'SAN', name: 'San Andrés y Providencia' },
        { code: 'SUC', name: 'Sucre' },
        { code: 'TOL', name: 'Tolima' },
        { code: 'VAL', name: 'Valle del Cauca' },
        { code: 'VAU', name: 'Vaupés' },
        { code: 'VID', name: 'Vichada' }
    ],
    '310': [ // Comoros
        { code: 'A', name: 'Anjouan' },
        { code: 'M', name: 'Mohéli' },
        { code: 'N', name: 'Ngazidja' }
    ],
    '311': [ // Ivory Coast (Côte d'Ivoire)
        { code: 'AB', name: 'Abidjan' },
        { code: 'AG', name: 'Agneby' },
        { code: 'BZ', name: 'Bouaké' },
        { code: 'GB', name: 'Gôh' },
        { code: 'GR', name: 'Grands Ponts' },
        { code: 'IK', name: 'Iffou' },
        { code: 'LC', name: 'Lacs' },
        { code: 'MO', name: 'Montagnes' },
        { code: 'ND', name: 'Nawa' },
        { code: 'SE', name: 'Savanes' },
        { code: 'VK', name: 'Vallée du Bandama' },
        { code: 'WZ', name: 'Worodougou' }
    ],
    '52': [ // Costa Rica
        { code: 'AL', name: 'Alajuela' },
        { code: 'CO', name: 'Cartago' },
        { code: 'GUA', name: 'Guanacaste' },
        { code: 'HER', name: 'Heredia' },
        { code: 'PUN', name: 'Puntarenas' },
        { code: 'SAN', name: 'San José' }
    ],
    '54': [ // Croatia
        { code: '01', name: 'Zagreb' },
        { code: '02', name: 'Krapina-Zagorje' },
        { code: '03', name: 'Sisak-Moslavina' },
        { code: '04', name: 'Karlovac' },
        { code: '05', name: 'Varaždin' },
        { code: '06', name: 'Međimurje' },
        { code: '07', name: 'Osijek-Baranja' },
        { code: '08', name: 'Virovitica-Podravina' },
        { code: '09', name: 'Požega-Slavonia' },
        { code: '10', name: 'Brod-Posavina' },
        { code: '11', name: 'Zadar' },
        { code: '12', name: 'Šibenik-Knin' },
        { code: '13', name: 'Split-Dalmatia' },
        { code: '14', name: 'Istria' },
        { code: '15', name: 'Lika-Senj' },
        { code: '16', name: 'Primorje-Gorski Kotar' },
        { code: '17', name: 'Zagreb' }
    ],
    '56': [ // Cyprus
        { code: 'F', name: 'Famagusta' },
        { code: 'K', name: 'Kyrenia' },
        { code: 'L', name: 'Larnaca' },
        { code: 'N', name: 'Nicosia' },
        { code: 'P', name: 'Paphos' },
        { code: 'S', name: 'Limassol' }
    ],
    '57': [ // Czech Republic
        { code: 'H', name: 'Hlavní město Praha' },
        { code: 'JC', name: 'Jihočeský kraj' },
        { code: 'JM', name: 'Jihomoravský kraj' },
        { code: 'KA', name: 'Karlovarský kraj' },
        { code: 'KM', name: 'Kraj Vysočina' },
        { code: 'MS', name: 'Moravskoslezský kraj' },
        { code: 'OL', name: 'Olomoucký kraj' },
        { code: 'PA', name: 'Pardubický kraj' },
        { code: 'PL', name: 'Plzeňský kraj' },
        { code: 'ST', name: 'Středočeský kraj' },
        { code: 'US', name: 'Ústecký kraj' },
        { code: 'ZS', name: 'Zlínský kraj' }
    ],
    '58': [ // Denmark
        { code: '81', name: 'Copenhagen' },
        { code: '82', name: 'North Denmark Region' },
        { code: '83', name: 'Central Jutland Region' },
        { code: '84', name: 'South Denmark' },
        { code: '85', name: 'Zealand' }
    ],
    '60': [ // Dominica
        { code: '01', name: 'Saint George' },
        { code: '02', name: 'Saint John' },
        { code: '03', name: 'Saint Joseph' },
        { code: '04', name: 'Saint Luke' },
        { code: '05', name: 'Saint Mark' },
        { code: '06', name: 'Saint Patrick' }
    ],
    '63': [ // Ecuador
        { code: 'A', name: 'Azuay' },
        { code: 'B', name: 'Bolívar' },
        { code: 'C', name: 'Cañar' },
        { code: 'D', name: 'Carchi' },
        { code: 'E', name: 'Chimborazo' },
        { code: 'F', name: 'Cotopaxi' },
        { code: 'G', name: 'El Oro' },
        { code: 'H', name: 'Esmeraldas' },
        { code: 'I', name: 'Galápagos' },
        { code: 'J', name: 'Guayas' },
        { code: 'K', name: 'Los Ríos' },
        { code: 'L', name: 'Manabí' },
        { code: 'M', name: 'Morona Santiago' },
        { code: 'N', name: 'Napo' },
        { code: 'O', name: 'Orellana' },
        { code: 'P', name: 'Pastaza' },
        { code: 'Q', name: 'Pichincha' },
        { code: 'R', name: 'Tungurahua' },
        { code: 'S', name: 'Zamora-Chinchipe' }
    ],
    '64': [ // Egypt
        { code: 'C', name: 'Cairo' },
        { code: 'G', name: 'Giza' },
        { code: 'Q', name: 'Qalyubia' },
        { code: 'D', name: 'Daqahlia' },
        { code: 'K', name: 'Kafr el-Sheikh' },
        { code: 'S', name: 'Suhaj' },
        { code: 'B', name: 'Beheira' },
        { code: 'F', name: 'Faiyum' },
        { code: 'N', name: 'North Sinai' },
        { code: 'S', name: 'South Sinai' },
        { code: 'L', name: 'Luxor' },
        { code: 'A', name: 'Aswan' },
        { code: 'M', name: 'Minya' },
        { code: 'Q', name: 'Qena' },
        { code: 'S', name: 'Sohag' },
        { code: 'W', name: 'Red Sea' },
        { code: 'B', name: 'Beni Suef' },
        { code: 'S', name: 'Sharqia' },
        { code: 'D', name: 'Dakhla Oasis' }
    ],
    '65': [ // El Salvador
        { code: 'AH', name: 'Ahuachapan' },
        { code: 'CA', name: 'Cabañas' },
        { code: 'CH', name: 'Chalatenango' },
        { code: 'CU', name: 'Cuscatlán' },
        { code: 'LA', name: 'La Libertad' },
        { code: 'MO', name: 'Morazán' },
        { code: 'SS', name: 'San Salvador' },
        { code: 'SM', name: 'San Vicente' },
        { code: 'SO', name: 'Sonsonate' },
        { code: 'US', name: 'Usulután' }
    ],

    '313': [ // Eritrea
        { code: 'AN', name: 'Anseba' },
        { code: 'DG', name: 'Debub' },
        { code: 'DS', name: 'Debub-Keih Bahri' },
        { code: 'GB', name: 'Gash-Barka' },
        { code: 'MA', name: 'Maekel' },
        { code: 'SK', name: 'Semen' },
        { code: 'KA', name: 'Southern Red Sea' }
    ],
    '205': [ // Spain
        { code: 'AB', name: 'Ávila' },
        { code: 'AL', name: 'Albacete' },
        { code: 'AN', name: 'Andalusia' },
        { code: 'AM', name: 'Almería' },
        { code: 'AR', name: 'Aragón' },
        { code: 'AS', name: 'Asturias' },
        { code: 'AV', name: 'Ávila' },
        { code: 'BA', name: 'Badajoz' },
        { code: 'BI', name: 'Bizkaia' },
        { code: 'BU', name: 'Burgos' },
        { code: 'CA', name: 'Cádiz' },
        { code: 'CE', name: 'Ceuta' },
        { code: 'CO', name: 'Córdoba' },
        { code: 'CU', name: 'Cuenca' },
        { code: 'GI', name: 'Girona' },
        { code: 'GR', name: 'Granada' },
        { code: 'GZ', name: 'Guipúzcoa' },
        { code: 'LE', name: 'León' },
        { code: 'LO', name: 'La Rioja' },
        { code: 'LA', name: 'La Coruña' },
        { code: 'LU', name: 'Lugo' },
        { code: 'MA', name: 'Madrid' },
        { code: 'MD', name: 'Málaga' },
        { code: 'MU', name: 'Murcia' },
        { code: 'NA', name: 'Navarra' },
        { code: 'OR', name: 'Ourense' },
        { code: 'PO', name: 'Pontevedra' },
        { code: 'SA', name: 'Salamanca' },
        { code: 'SG', name: 'Segovia' },
        { code: 'SO', name: 'Soria' },
        { code: 'TA', name: 'Tarragona' },
        { code: 'TE', name: 'Teruel' },
        { code: 'TO', name: 'Toledo' },
        { code: 'VC', name: 'Valencia' },
        { code: 'ZA', name: 'Zamora' },
        { code: 'ZB', name: 'Zaragoza' }
    ],
    '68': [ // Estonia
        { code: '37', name: 'Harju' },
        { code: '44', name: 'Hiiu' },
        { code: '49', name: 'Ida-Viru' },
        { code: '60', name: 'Jõgeva' },
        { code: '61', name: 'Järva' },
        { code: '65', name: 'Lääne' },
        { code: '66', name: 'Lääne-Viru' },
        { code: '74', name: 'Pärnu' },
        { code: '75', name: 'Põlva' },
        { code: '77', name: 'Saare' },
        { code: '78', name: 'Tartu' },
        { code: '80', name: 'Valga' },
        { code: '81', name: 'Viljandi' },
        { code: '82', name: 'Võru' }
    ],
    '314': [ // Ethiopia
        { code: 'AA', name: 'Addis Ababa' },
        { code: 'AF', name: 'Afar' },
        { code: 'AM', name: 'Amhara' },
        { code: 'BG', name: 'Benishangul-Gumuz' },
        { code: 'DD', name: 'Dire Dawa' },
        { code: 'GE', name: 'Gambela' },
        { code: 'HG', name: 'Harari' },
        { code: 'OR', name: 'Oromia' },
        { code: 'SM', name: 'Somali' },
        { code: 'SN', name: 'Southern Nations, Nationalities, and Peoples' },
        { code: 'TI', name: 'Tigray' }
    ],
    '71': [ // Falkland Islands
        { code: 'FI', name: 'Falkland Islands' }
    ],
    '72': [ // Faroe Islands
        { code: 'FO', name: 'Faroe Islands' }
    ],
    '74': [ // Finland
        { code: 'AL', name: 'Åland Islands' },
        { code: 'ES', name: 'Etelä-Suomi' },
        { code: 'PH', name: 'Pohjois-Suomi' },
        { code: 'PK', name: 'Pohjois-Karjala' },
        { code: 'SU', name: 'Satakunta' },
        { code: 'TA', name: 'Tampere' },
        { code: 'US', name: 'Uusimaa' }
    ],
    '75': [ // France
        { code: '01', name: 'Ain' },
        { code: '02', name: 'Aisne' },
        { code: '03', name: 'Allier' },
        { code: '04', name: 'Alpes-de-Haute-Provence' },
        { code: '05', name: 'Hautes-Alpes' },
        { code: '06', name: 'Alpes-Maritimes' },
        { code: '07', name: 'Ardèche' },
        { code: '08', name: 'Ardennes' },
        { code: '09', name: 'Ariège' },
        { code: '10', name: 'Aube' },
        { code: '11', name: 'Aude' },
        { code: '12', name: 'Aveyron' },
        { code: '13', name: 'Bouches-du-Rhône' },
        { code: '14', name: 'Calvados' },
        { code: '15', name: 'Cantal' },
        { code: '16', name: 'Charente' },
        { code: '17', name: 'Charente-Maritime' },
        { code: '18', name: 'Cher' },
        { code: '19', name: 'Corrèze' },
        { code: '2A', name: 'Corse-du-Sud' },
        { code: '2B', name: 'Haute-Corse' },
        { code: '21', name: 'Côte-d\'Or' },
        { code: '22', name: 'Côtes-d\'Armor' },
        { code: '23', name: 'Creuse' },
        { code: '24', name: 'Dordogne' },
        { code: '25', name: 'Doubs' },
        { code: '26', name: 'Drôme' },
        { code: '27', name: 'Eure' },
        { code: '28', name: 'Eure-et-Loir' },
        { code: '29', name: 'Finistère' },
        { code: '30', name: 'Gard' },
        { code: '31', name: 'Haute-Garonne' },
        { code: '32', name: 'Gers' },
        { code: '33', name: 'Gironde' },
        { code: '34', name: 'Hérault' },
        { code: '35', name: 'Ille-et-Vilaine' },
        { code: '36', name: 'Indre' },
        { code: '37', name: 'Indre-et-Loire' },
        { code: '38', name: 'Isère' },
        { code: '39', name: 'Jura' },
        { code: '40', name: 'Landes' },
        { code: '41', name: 'Loir-et-Cher' },
        { code: '42', name: 'Loire' },
        { code: '43', name: 'Haute-Loire' },
        { code: '44', name: 'Loire-Atlantique' },
        { code: '45', name: 'Loiret' },
        { code: '46', name: 'Lot' },
        { code: '47', name: 'Lot-et-Garonne' },
        { code: '48', name: 'Lozère' },
        { code: '49', name: 'Maine-et-Loire' },
        { code: '50', name: 'Manche' },
        { code: '51', name: 'Marne' },
        { code: '52', name: 'Haute-Marne' },
        { code: '53', name: 'Mayenne' },
        { code: '54', name: 'Meurthe-et-Moselle' },
        { code: '55', name: 'Meuse' },
        { code: '56', name: 'Morbihan' },
        { code: '57', name: 'Moselle' },
        { code: '58', name: 'Nièvre' },
        { code: '59', name: 'Nord' },
        { code: '60', name: 'Oise' },
        { code: '61', name: 'Orne' },
        { code: '62', name: 'Pas-de-Calais' },
        { code: '63', name: 'Puy-de-Dôme' },
        { code: '64', name: 'Pyrénées-Atlantiques' },
        { code: '65', name: 'Hautes-Pyrénées' },
        { code: '66', name: 'Pyrénées-Orientales' },
        { code: '67', name: 'Bas-Rhin' },
        { code: '68', name: 'Haut-Rhin' },
        { code: '69', name: 'Rhône' },
        { code: '70', name: 'Haute-Saône' },
        { code: '71', name: 'Saône-et-Loire' },
        { code: '72', name: 'Sarthe' },
        { code: '73', name: 'Savoie' },
        { code: '74', name: 'Haute-Savoie' },
        { code: '75', name: 'Paris' },
        { code: '76', name: 'Seine-Maritime' },
        { code: '77', name: 'Seine-et-Marne' },
        { code: '78', name: 'Yvelines' },
        { code: '79', name: 'Deux-Sèvres' },
        { code: '80', name: 'Somme' },
        { code: '81', name: 'Tarn' },
        { code: '82', name: 'Tarn-et-Garonne' },
        { code: '83', name: 'Var' },
        { code: '84', name: 'Vaucluse' },
        { code: '85', name: 'Vendée' },
        { code: '86', name: 'Vienne' },
        { code: '87', name: 'Haute-Vienne' },
        { code: '88', name: 'Vosges' },
        { code: '89', name: 'Yonne' },
        { code: '90', name: 'Territoire de Belfort' },
        { code: '91', name: 'Essonne' },
        { code: '92', name: 'Hauts-de-Seine' },
        { code: '93', name: 'Seine-Saint-Denis' },
        { code: '94', name: 'Val-de-Marne' },
        { code: '95', name: 'Val-d\'Oise' },
        { code: '976', name: 'Mayotte' },
        { code: '977', name: 'Réunion' },
        { code: '971', name: 'Guadeloupe' },
        { code: '972', name: 'Martinique' },
        { code: '973', name: 'Guyane' },
        { code: '974', name: 'La Réunion' }
    ],
    '76': [ // French Guiana
        { code: 'GF', name: 'French Guiana' }
    ],
    '315': [ // Gabon
        { code: 'ES', name: 'Estuaire' },
        { code: 'OW', name: 'Ogooué-Lolo' },
        { code: 'AK', name: 'Ogooué-Ivindo' },
        { code: 'NE', name: 'Ngounié' },
        { code: 'MO', name: 'Moyen-Ogooué' },
        { code: 'WU', name: 'Woleu-Ntem' },
        { code: 'OH', name: 'Ogooué-Maritime' }
    ],
    '316': [ // Gambia
        { code: 'B', name: 'Banjul' },
        { code: 'M', name: 'Mansa Konko' },
        { code: 'W', name: 'Western' }
    ],
    '81': [ // Georgia
        { code: 'AB', name: 'Abkhazia' },
        { code: 'AJ', name: 'Adjara' },
        { code: 'GG', name: 'Guria' },
        { code: 'KA', name: 'Kakheti' },
        { code: 'KK', name: 'Kvemo Kartli' },
        { code: 'MM', name: 'Mtskheta-Mtianeti' },
        { code: 'RM', name: 'Racha-Lechkhumi and Kvemo Svaneti' },
        { code: 'SK', name: 'Samtskhe-Javakheti' },
        { code: 'SJ', name: 'Samegrelo-Zemo Svaneti' },
        { code: 'TB', name: 'Tbilisi' },
        { code: 'ZZ', name: 'Zemo Svaneti' }
    ],
    '82': [ // Germany
        { code: 'BW', name: 'Baden-Württemberg' },
        { code: 'BY', name: 'Bavaria' },
        { code: 'BE', name: 'Berlin' },
        { code: 'BB', name: 'Brandenburg' },
        { code: 'HB', name: 'Bremen' },
        { code: 'HH', name: 'Hamburg' },
        { code: 'HE', name: 'Hesse' },
        { code: 'MV', name: 'Mecklenburg-Vorpommern' },
        { code: 'NI', name: 'Lower Saxony' },
        { code: 'NW', name: 'North Rhine-Westphalia' },
        { code: 'RP', name: 'Rhineland-Palatinate' },
        { code: 'SL', name: 'Saarland' },
        { code: 'SN', name: 'Saxony' },
        { code: 'ST', name: 'Saxony-Anhalt' },
        { code: 'SH', name: 'Schleswig-Holstein' },
        { code: 'TH', name: 'Thuringia' }
    ],
    '317': [ // Ghana
        { code: 'AA', name: 'Greater Accra' },
        { code: 'BA', name: 'Brong-Ahafo' },
        { code: 'CR', name: 'Central' },
        { code: 'EP', name: 'Eastern' },
        { code: 'NE', name: 'Northern' },
        { code: 'UE', name: 'Upper East' },
        { code: 'UW', name: 'Upper West' },
        { code: 'VO', name: 'Volta' },
        { code: 'WE', name: 'Western' }
    ],
    '84': [ // Gibraltar
        { code: 'G', name: 'Gibraltar' }
    ],
    '85': [ // Greece
        { code: 'AT', name: 'Aitolia-Acarnania' },
        { code: 'AR', name: 'Argolis' },
        { code: 'AX', name: 'Achaea' },
        { code: 'BE', name: 'Béotia' },
        { code: 'CF', name: 'Chalkidiki' },
        { code: 'CS', name: 'Chios' },
        { code: 'DK', name: 'Dodecanese' },
        { code: 'ET', name: 'Epirus' },
        { code: 'IM', name: 'Imathia' },
        { code: 'KV', name: 'Kavala' },
        { code: 'KE', name: 'Kefalonia' },
        { code: 'ME', name: 'Macedonia' },
        { code: 'NA', name: 'Naxos' },
        { code: 'PL', name: 'Pella' },
        { code: 'RF', name: 'Rethymno' },
        { code: 'RO', name: 'Rodopí' },
        { code: 'SK', name: 'Samos' },
        { code: 'TH', name: 'Thessaloniki' },
        { code: 'ZK', name: 'Zagori' }
    ],
    '86': [ // Greenland
        { code: 'QA', name: 'Qaasuitsup' },
        { code: 'QA', name: 'Qeqqata' },
        { code: 'GL', name: 'Sermersooq' },
        { code: 'TI', name: 'Tasiilaq' },
        { code: 'NP', name: 'Nanortalik' }
    ],
    '87': [ // Grenada
        { code: 'AN', name: 'Saint Andrew' },
        { code: 'GS', name: 'Saint George' },
        { code: 'HM', name: 'Saint Mark' },
        { code: 'ST', name: 'Saint Patrick' }
    ],
    '88': [ // Guadeloupe
        { code: 'GU', name: 'Guadeloupe' }
    ],
    '90': [ // Guatemala
        { code: 'AV', name: 'Alta Verapaz' },
        { code: 'BZ', name: 'Baja Verapaz' },
        { code: 'CH', name: 'Chimaltenango' },
        { code: 'CN', name: 'Chiquimula' },
        { code: 'ES', name: 'Escuintla' },
        { code: 'GU', name: 'Guatemala' },
        { code: 'HM', name: 'Huehuetenango' },
        { code: 'IZ', name: 'Izabal' },
        { code: 'JA', name: 'Jalapa' },
        { code: 'MC', name: 'Mixco' },
        { code: 'PM', name: 'Peten' },
        { code: 'PQ', name: 'Progreso' },
        { code: 'QZ', name: 'Quetzaltenango' },
        { code: 'RE', name: 'Retalhuleu' },
        { code: 'SO', name: 'Santa Rosa' },
        { code: 'SU', name: 'San Marcos' },
        { code: 'TO', name: 'Totonicapán' },
        { code: 'ZA', name: 'Zacapa' }
    ],
    '94': [ // Guiana
        { code: 'GU', name: 'Guiana' }
    ],
    '318': [ // Guinea
        { code: 'GA', name: 'Guinea' }
    ],
    '320': [ // Guinea Ecuatorial
        { code: 'AN', name: 'Annobón' },
        { code: 'BI', name: 'Bioko Norte' },
        { code: 'CA', name: 'Centro Sur' },
        { code: 'CO', name: 'Coalition' },
        { code: 'WA', name: 'Wele-Nzas' },
        { code: 'EG', name: 'Escrutini' },
        { code: 'CA', name: 'Cruz Grande' },
        { code: 'LO', name: 'Litoral' },
        { code: 'NE', name: 'Niefang' },
        { code: 'NS', name: 'Nfo' }
    ],
    '319': [ // Guinea-Bissau
        { code: 'BA', name: 'Bafatá' },
        { code: 'BI', name: 'Biombo' },
        { code: 'BM', name: 'Bolama' },
        { code: 'GA', name: 'Gabú' },
        { code: 'QU', name: 'Quinara' },
        { code: 'TO', name: 'Tombali' }
    ],
    '97': [ // Honduras
        { code: 'AT', name: 'Atlántida' },
        { code: 'CH', name: 'Choluteca' },
        { code: 'CO', name: 'Colón' },
        { code: 'CP', name: 'Copán' },
        { code: 'CR', name: 'Cortes' },
        { code: 'DG', name: 'Gracias a Dios' },
        { code: 'HD', name: 'Honduras' },
        { code: 'LA', name: 'La Paz' },
        { code: 'OC', name: 'Ocotepeque' },
        { code: 'OL', name: 'Olancho' },
        { code: 'SB', name: 'Santa Bárbara' },
        { code: 'YO', name: 'Yoro' }
    ],
    '99': [ // Hungary
        { code: 'B', name: 'Budapest' },
        { code: 'C', name: 'Csongrád' },
        { code: 'DE', name: 'Debrecen' },
        { code: 'FE', name: 'Fejér' },
        { code: 'GS', name: 'Győr-Moson-Sopron' },
        { code: 'HN', name: 'Hajdú-Bihar' },
        { code: 'NO', name: 'Nógrád' },
        { code: 'PE', name: 'Pest' },
        { code: 'SO', name: 'Somogy' },
        { code: 'SZ', name: 'Szabolcs-Szatmár-Bereg' },
        { code: 'TO', name: 'Tolna' },
        { code: 'VA', name: 'Vas' },
        { code: 'VE', name: 'Veszprém' },
        { code: 'ZA', name: 'Zala' }
    ],
    '100': [ // Iceland
        { code: 'SN', name: 'Snæfellsnes' },
        { code: 'SU', name: 'Suðurland' },
        { code: 'NA', name: 'Norðurland eystra' },
        { code: 'NV', name: 'Norðurland vestra' },
        { code: 'RE', name: 'Reykjavik' },
        { code: 'SE', name: 'Suðurnes' },
        { code: 'WI', name: 'Vesturland' },
        { code: 'WU', name: 'Vestfirðir' }
    ],
    
    '352': [ // Iraq
        { code: 'AN', name: 'Al Anbar' },
        { code: 'BA', name: 'Baghdad' },
        { code: 'DA', name: 'Dahuk' },
        { code: 'DI', name: 'Diyala' },
        { code: 'KA', name: 'Karbala' },
        { code: 'MA', name: 'Muthanna' },
        { code: 'NA', name: 'Ninawa' },
        { code: 'QA', name: 'Qadisiyyah' },
        { code: 'SA', name: 'Saladin' },
        { code: 'SU', name: 'Sulaymaniyah' },
        { code: 'TA', name: 'Tamim' },
        { code: 'TH', name: 'Thi Qar' },
        { code: 'WA', name: 'Wasit' }
    ],
    '105': [ // Ireland
        { code: 'C', name: 'Carlow' },
        { code: 'CAV', name: 'Cavan' },
        { code: 'CORK', name: 'Cork' },
        { code: 'D', name: 'Dublin' },
        { code: 'DL', name: 'Donegal' },
        { code: 'DR', name: 'Down' },
        { code: 'FER', name: 'Fermanagh' },
        { code: 'GAL', name: 'Galway' },
        { code: 'K', name: 'Kerry' },
        { code: 'KK', name: 'Kilkenny' },
        { code: 'LAO', name: 'Laois' },
        { code: 'LEI', name: 'Leitrim' },
        { code: 'LIM', name: 'Limerick' },
        { code: 'LONG', name: 'Longford' },
        { code: 'LOUTH', name: 'Louth' },
        { code: 'MAY', name: 'Mayo' },
        { code: 'ME', name: 'Meath' },
        { code: 'OFF', name: 'Offaly' },
        { code: 'RO', name: 'Roscommon' },
        { code: 'SL', name: 'Sligo' },
        { code: 'TIP', name: 'Tipperary' },
        { code: 'WEX', name: 'Wexford' },
        { code: 'WME', name: 'Westmeath' },
        { code: 'WICK', name: 'Wicklow' },
        { code: 'WATER', name: 'Waterford' }
    ],
    '107': [ // Italy
        { code: 'AG', name: 'Agrigento' },
        { code: 'AL', name: 'Alessandria' },
        { code: 'AN', name: 'Ancona' },
        { code: 'AO', name: 'Aosta' },
        { code: 'AR', name: 'Arezzo' },
        { code: 'AP', name: 'Ascoli Piceno' },
        { code: 'AT', name: 'Asti' },
        { code: 'AV', name: 'Avellino' },
        { code: 'BA', name: 'Bari' },
        { code: 'BL', name: 'Belluno' },
        { code: 'BN', name: 'Benevento' },
        { code: 'BG', name: 'Bergamo' },
        { code: 'BI', name: 'Biella' },
        { code: 'BO', name: 'Bologna' },
        { code: 'BR', name: 'Brindisi' },
        { code: 'BS', name: 'Brescia' },
        { code: 'CA', name: 'Cagliari' },
        { code: 'CB', name: 'Campobasso' },
        { code: 'CE', name: 'Caserta' },
        { code: 'CH', name: 'Chieti' },
        { code: 'CN', name: 'Cuneo' },
        { code: 'CR', name: 'Cremona' },
        { code: 'CS', name: 'Cosenza' },
        { code: 'CT', name: 'Catania' },
        { code: 'EN', name: 'Enna' },
        { code: 'FM', name: 'Fermo' },
        { code: 'FG', name: 'Foggia' },
        { code: 'FR', name: 'Frosinone' },
        { code: 'GE', name: 'Genoa' },
        { code: 'GO', name: 'Gorizia' },
        { code: 'GR', name: 'Grosseto' },
        { code: 'IM', name: 'Imperia' },
        { code: 'IS', name: 'Isernia' },
        { code: 'KR', name: 'Crotone' },
        { code: 'LT', name: 'Latina' },
        { code: 'LE', name: 'Lecce' },
        { code: 'LI', name: 'Livorno' },
        { code: 'LO', name: 'Lodi' },
        { code: 'LU', name: 'Lucca' },
        { code: 'MC', name: 'Macerata' },
        { code: 'ME', name: 'Messina' },
        { code: 'MI', name: 'Milan' },
        { code: 'MN', name: 'Mantua' },
        { code: 'MS', name: 'Massa-Carrara' },
        { code: 'NA', name: 'Naples' },
        { code: 'NO', name: 'Novara' },
        { code: 'NU', name: 'Nuoro' },
        { code: 'OR', name: 'Oristano' },
        { code: 'OT', name: 'Olbia-Tempio' },
        { code: 'PD', name: 'Padua' },
        { code: 'PE', name: 'Perugia' },
        { code: 'PG', name: 'Piacenza' },
        { code: 'PI', name: 'Pisa' },
        { code: 'PN', name: 'Pordenone' },
        { code: 'PT', name: 'Prato' },
        { code: 'RA', name: 'Ragusa' },
        { code: 'RE', name: 'Reggio Emilia' },
        { code: 'RI', name: 'Rieti' },
        { code: 'RM', name: 'Rome' },
        { code: 'RN', name: 'Rimini' },
        { code: 'RO', name: 'Rovigo' },
        { code: 'SA', name: 'Salerno' },
        { code: 'SI', name: 'Siena' },
        { code: 'SO', name: 'Sondrio' },
        { code: 'SP', name: 'La Spezia' },
        { code: 'SR', name: 'Siracusa' },
        { code: 'TA', name: 'Taranto' },
        { code: 'TE', name: 'Teramo' },
        { code: 'TN', name: 'Trento' },
        { code: 'TV', name: 'Treviso' },
        { code: 'UD', name: 'Udine' },
        { code: 'VB', name: 'Verbano-Cusio-Ossola' },
        { code: 'VC', name: 'Vercelli' },
        { code: 'VR', name: 'Verona' },
        { code: 'VT', name: 'Viterbo' }
    ],
    '108': [ // Jamaica
        { code: '02', name: 'Clarendon' },
        { code: '03', name: 'Hanover' },
        { code: '04', name: 'Kingston' },
        { code: '05', name: 'Manchester' },
        { code: '06', name: 'Portland' },
        { code: '07', name: 'St. Andrew' },
        { code: '08', name: 'St. Ann' },
        { code: '09', name: 'St. Catherine' },
        { code: '10', name: 'St. Elizabeth' },
        { code: '11', name: 'St. James' },
        { code: '12', name: 'St. Mary' },
        { code: '13', name: 'St. Thomas' },
        { code: '14', name: 'Trelawny' },
        { code: '15', name: 'Westmoreland' }
    ],
    '109': [ // Japan
        { code: '01', name: 'Aichi' },
        { code: '02', name: 'Akita' },
        { code: '03', name: 'Aomori' },
        { code: '04', name: 'Chiba' },
        { code: '05', name: 'Ehime' },
        { code: '06', name: 'Fukui' },
        { code: '07', name: 'Fukuoka' },
        { code: '08', name: 'Gifu' },
        { code: '09', name: 'Gunma' },
        { code: '10', name: 'Hiroshima' },
        { code: '11', name: 'Hokkaido' },
        { code: '12', name: 'Hyogo' },
        { code: '13', name: 'Ibaraki' },
        { code: '14', name: 'Ishikawa' },
        { code: '15', name: 'Iwate' },
        { code: '16', name: 'Kagawa' },
        { code: '17', name: 'Kagoshima' },
        { code: '18', name: 'Kanagawa' },
        { code: '19', name: 'Kochi' },
        { code: '20', name: 'Kumamoto' },
        { code: '21', name: 'Kyoto' },
        { code: '22', name: 'Miyagi' },
        { code: '23', name: 'Miyazaki' },
        { code: '24', name: 'Nagano' },
        { code: '25', name: 'Nagasaki' },
        { code: '26', name: 'Niigata' },
        { code: '27', name: 'Oita' },
        { code: '28', name: 'Okayama' },
        { code: '29', name: 'Okinawa' },
        { code: '30', name: 'Osaka' },
        { code: '31', name: 'Saga' },
        { code: '32', name: 'Shiga' },
        { code: '33', name: 'Shimane' },
        { code: '34', name: 'Shizuoka' },
        { code: '35', name: 'Tochigi' },
        { code: '36', name: 'Tokushima' },
        { code: '37', name: 'Tokyo' },
        { code: '38', name: 'Yamagata' },
        { code: '39', name: 'Yamaguchi' },
        { code: '40', name: 'Yamanashi' }
    ],
    '321': [ // Kenya
        { code: '01', name: 'Bomet' },
        { code: '02', name: 'Bungoma' },
        { code: '03', name: 'Busia' },
        { code: '04', name: 'Elgeyo-Marakwet' },
        { code: '05', name: 'Embu' },
        { code: '06', name: 'Garissa' },
        { code: '07', name: 'Homa Bay' },
        { code: '08', name: 'Isiolo' },
        { code: '09', name: 'Kajiado' },
        { code: '10', name: 'Kakamega' },
        { code: '11', name: 'Kericho' },
        { code: '12', name: 'Kiambu' },
        { code: '13', name: 'Kilifi' },
        { code: '14', name: 'Kirinyaga' },
        { code: '15', name: 'Kisii' },
        { code: '16', name: 'Kisumu' },
        { code: '17', name: 'Kitui' },
        { code: '18', name: 'Kwale' },
        { code: '19', name: 'Laikipia' },
        { code: '20', name: 'Lamu' },
        { code: '21', name: 'Machakos' },
        { code: '22', name: 'Makueni' },
        { code: '23', name: 'Mandera' },
        { code: '24', name: 'Marsabit' },
        { code: '25', name: 'Meru' },
        { code: '26', name: 'Migori' },
        { code: '27', name: 'Nairobi City' },
        { code: '28', name: 'Nakuru' },
        { code: '29', name: 'Nandi' },
        { code: '30', name: 'Narok' },
        { code: '31', name: 'Nyandarua' },
        { code: '32', name: 'Nyeri' },
        { code: '33', name: 'Samburu' },
        { code: '34', name: 'Siaya' },
        { code: '35', name: 'Taita Taveta' },
        { code: '36', name: 'Tana River' },
        { code: '37', name: 'Tharaka Nithi' },
        { code: '38', name: 'Trans Nzoia' },
        { code: '39', name: 'Turkana' },
        { code: '40', name: 'Uasin Gishu' },
        { code: '41', name: 'Vihiga' },
        { code: '42', name: 'Wajir' },
        { code: '43', name: 'West Pokot' },
        { code: '44', name: 'Nyamira' }
    ],
    '120': [ // Latvia
        { code: 'AL', name: 'Aizkraukles' },
        { code: 'BA', name: 'Bauskas' },
        { code: 'DO', name: 'Daugavpils' },
        { code: 'GR', name: 'Grobiņas' },
        { code: 'JA', name: 'Jelgavas' },
        { code: 'JO', name: 'Jūrmala' },
        { code: 'KO', name: 'Kocēnu' },
        { code: 'KR', name: 'Krāslavas' },
        { code: 'KO', name: 'Kuldīgas' },
        { code: 'OG', name: 'Ogres' },
        { code: 'RE', name: 'Rēzeknes' },
        { code: 'TO', name: 'Tukuma' },
        { code: 'VL', name: 'Ventspils' }
    ],
    '322': [ // Lesotho
        { code: 'B', name: 'Berea' },
        { code: 'D', name: 'District of Maseru' },
        { code: 'M', name: 'Mafeteng' },
        { code: 'M', name: 'Mokhotlong' },
        { code: 'Q', name: 'Qacha’s Nek' },
        { code: 'T', name: 'Thaba-Tseka' },
        { code: 'L', name: 'Leribe' },
        { code: 'H', name: 'Quthing' },
        { code: 'M', name: 'Maseru' }
    ],
    '323': [ // Liberia
        { code: 'BM', name: 'Bong' },
        { code: 'GB', name: 'Grand Bassa' },
        { code: 'GG', name: 'Grand Gedeh' },
        { code: 'LR', name: 'Lofa' },
        { code: 'MG', name: 'Margibi' },
        { code: 'MR', name: 'Maryland' },
        { code: 'MG', name: 'Montserrado' },
        { code: 'NB', name: 'Nimba' },
        { code: 'RG', name: 'River Gee' },
        { code: 'SL', name: 'Sinoe' }
    ],
    '324': [ // Libya
        { code: 'AL', name: 'Al Kufrah' },
        { code: 'BZ', name: 'Benghazi' },
        { code: 'FA', name: 'Fayzā' },
        { code: 'MA', name: 'Misrata' },
        { code: 'TB', name: 'Tripoli' },
        { code: 'WB', name: 'Wadi al Shatii' }
    ],
    '125': [ // Liechtenstein
        { code: 'LI', name: 'Liechtenstein' }
    ],
    '126': [ // Lithuania
        { code: 'AL', name: 'Alytaus' },
        { code: 'KU', name: 'Kaunas' },
        { code: 'KL', name: 'Klaipeda' },
        { code: 'MA', name: 'Marijampolė' },
        { code: 'TA', name: 'Tauragė' },
        { code: 'UT', name: 'Utena' },
        { code: 'VL', name: 'Vilnius' }
    ],
    '127': [ // Luxembourg
        { code: 'LU', name: 'Luxembourg' }
    ],
    '129': [ // Macedonia
        { code: 'SK', name: 'Skopje' },
        { code: 'BT', name: 'Bitola' },
        { code: 'MK', name: 'Makedonija' },
        { code: 'OO', name: 'Ohrid' }
    ],
    '325': [ // Madagascar
        { code: 'AN', name: 'Antananarivo' },
        { code: 'AT', name: 'Antananarivo' },
        { code: 'TA', name: 'Toliara' },
        { code: 'TO', name: 'Toamasina' }
    ],
    '326': [ // Malawi
        { code: 'BL', name: 'Blantyre' },
        { code: 'CK', name: 'Chikwawa' },
        { code: 'DO', name: 'Dowa' },
        { code: 'LI', name: 'Lilongwe' },
        { code: 'MU', name: 'Mchinji' },
        { code: 'MG', name: 'Mulanje' },
        { code: 'NK', name: 'Nkhotakota' },
        { code: 'NS', name: 'Nsanje' },
        { code: 'NT', name: 'Ntcheu' },
        { code: 'NY', name: 'Nkhata Bay' },
        { code: 'PH', name: 'Phalombe' },
        { code: 'RU', name: 'Rumphi' },
        { code: 'SZ', name: 'Salima' },
        { code: 'TH', name: 'Thyolo' },
        { code: 'UC', name: 'Ulongwe' },
        { code: 'ZA', name: 'Zomba' }
    ],
    '327': [ // Mali
        { code: 'GA', name: 'Gao' },
        { code: 'KE', name: 'Kidal' },
        { code: 'KO', name: 'Koulikoro' },
        { code: 'LI', name: 'Liptako' },
        { code: 'MU', name: 'Mopti' },
        { code: 'SK', name: 'Sikasso' },
        { code: 'SY', name: 'Ségou' },
        { code: 'TB', name: 'Tombouctou' },
        { code: 'GA', name: 'Kayes' }
    ],
    '135': [ // Malta
        { code: '00', name: 'Malta' }
    ],

    '148': [ // Morocco
        { code: '01', name: 'Agadir' },
        { code: '02', name: 'Casablanca' },
        { code: '03', name: 'Fes' },
        { code: '04', name: 'Marrakech' },
        { code: '05', name: 'Ouarzazate' },
        { code: '06', name: 'Tangier' },
        { code: '07', name: 'Tetouan' },
        { code: '08', name: 'Rabat' },
        { code: '09', name: 'Essaouira' }
    ],
    '138': [ // Martinique
        { code: '01', name: 'Fort-de-France' },
        { code: '02', name: 'La Trinité' },
        { code: '03', name: 'Le Marin' },
        { code: '04', name: 'Saint-Pierre' }
    ],
    '328': [ // Mauritius
        { code: '01', name: 'Beau Bassin-Rose Hill' },
        { code: '02', name: 'Curepipe' },
        { code: '03', name: 'Port Louis' },
        { code: '04', name: 'Quatre Bornes' },
        { code: '05', name: 'Vacoas-Phoenix' }
    ],
    '329': [ // Mauritania
        { code: '01', name: 'Adrar' },
        { code: '02', name: 'Assaba' },
        { code: '03', name: 'Brakna' },
        { code: '04', name: 'Dakhlet Nouadhibou' },
        { code: '05', name: 'Gorgol' },
        { code: '06', name: 'Guidimaka' },
        { code: '07', name: 'Hodh Ech Chargui' },
        { code: '08', name: 'Hodh El Gharbi' },
        { code: '09', name: 'Inchiri' },
        { code: '10', name: 'Nouakchott' },
        { code: '11', name: 'Tagant' },
        { code: '12', name: 'Tiris Zemmour' },
        { code: '13', name: 'Trarza' }
    ],
    '142': [ // Mexico
        { code: 'AG', name: 'Aguascalientes' },
        { code: 'BC', name: 'Baja California' },
        { code: 'BS', name: 'Baja California Sur' },
        { code: 'CM', name: 'Campeche' },
        { code: 'CO', name: 'Coahuila' },
        { code: 'CL', name: 'Colima' },
        { code: 'CH', name: 'Chiapas' },
        { code: 'DF', name: 'Distrito Federal' },
        { code: 'DG', name: 'Durango' },
        { code: 'GT', name: 'Guanajuato' },
        { code: 'GR', name: 'Guerrero' },
        { code: 'HG', name: 'Hidalgo' },
        { code: 'JA', name: 'Jalisco' },
        { code: 'EM', name: 'México State' },
        { code: 'MI', name: 'Michoacán' },
        { code: 'MO', name: 'Morelos' },
        { code: 'NA', name: 'Nayarit' },
        { code: 'NL', name: 'Nuevo León' },
        { code: 'OA', name: 'Oaxaca' },
        { code: 'PU', name: 'Puebla' },
        { code: 'QE', name: 'Querétaro' },
        { code: 'QR', name: 'Quintana Roo' },
        { code: 'SL', name: 'San Luis Potosí' },
        { code: 'SI', name: 'Sinaloa' },
        { code: 'SO', name: 'Sonora' },
        { code: 'TB', name: 'Tabasco' },
        { code: 'TM', name: 'Tamaulipas' },
        { code: 'TL', name: 'Tlaxcala' },
        { code: 'VE', name: 'Veracruz' },
        { code: 'YU', name: 'Yucatán' },
        { code: 'ZA', name: 'Zacatecas' }
    ],
    '144': [ // Moldova
        { code: 'AN', name: 'Anenii Noi' },
        { code: 'BR', name: 'Briceni' },
        { code: 'CA', name: 'Cahul' },
        { code: 'CL', name: 'Călărași' },
        { code: 'CR', name: 'Cricova' },
        { code: 'DO', name: 'Dondușeni' },
        { code: 'DR', name: 'Drochia' },
        { code: 'GL', name: 'Glodeni' },
        { code: 'HN', name: 'Hîncești' },
        { code: 'LE', name: 'Leova' },
        { code: 'OR', name: 'Orhei' }
    ],
    '145': [ // Monaco
        { code: 'MO', name: 'Monaco' }
    ],
    '299': [ // Montenegro
        { code: '01', name: 'Andrijevica' },
        { code: '02', name: 'Bar' },
        { code: '03', name: 'Berane' },
        { code: '04', name: 'Bijelo Polje' },
        { code: '05', name: 'Budva' },
        { code: '06', name: 'Cetinje' },
        { code: '07', name: 'Danilovgrad' },
        { code: '08', name: 'Herceg Novi' },
        { code: '09', name: 'Kolašin' },
        { code: '10', name: 'Kotor' },
        { code: '11', name: 'Mojkovac' },
        { code: '12', name: 'Nikšić' },
        { code: '13', name: 'Plav' },
        { code: '14', name: 'Pljevlja' },
        { code: '15', name: 'Podgorica' },
        { code: '16', name: 'Rožaje' },
        { code: '17', name: 'Šavnik' },
        { code: '18', name: 'Tivat' },
        { code: '19', name: 'Ulcinj' },
        { code: '20', name: 'Žabljak' }
    ],
    '147': [ // Montserrat
        { code: '00', name: 'Montserrat' }
    ],
    '330': [ // Mozambique
        { code: 'A', name: 'Maputo' },
        { code: 'B', name: 'Beira' },
        { code: 'C', name: 'Chimoio' },
        { code: 'D', name: 'Nampula' },
        { code: 'E', name: 'Tete' }
    ],
    '332': [ // Niger
        { code: 'AG', name: 'Agadez' },
        { code: 'DI', name: 'Diffa' },
        { code: 'DO', name: 'Dosso' },
        { code: 'MA', name: 'Maradi' },
        { code: 'NI', name: 'Niamey' },
        { code: 'TI', name: 'Tillabéri' },
        { code: 'ZA', name: 'Zinder' }
    ],
    '331': [ // Namibia
        { code: 'ER', name: 'Erongo' },
        { code: 'HA', name: 'Hardap' },
        { code: 'KA', name: 'Karas' },
        { code: 'KH', name: 'Khomas' },
        { code: 'KU', name: 'Kunene' },
        { code: 'OD', name: 'Otjozondjupa' },
        { code: 'OH', name: 'Oshana' },
        { code: 'ON', name: 'Oshikoto' },
        { code: 'OM', name: 'Omusati' },
        { code: 'OO', name: 'Ohangwena' }
    ],
    '155': [ // Netherlands
        { code: 'DR', name: 'Drenthe' },
        { code: 'FL', name: 'Flevoland' },
        { code: 'FR', name: 'Friesland' },
        { code: 'GE', name: 'Gelderland' },
        { code: 'GR', name: 'Groningen' },
        { code: 'LI', name: 'Limburg' },
        { code: 'NB', name: 'North Brabant' },
        { code: 'NH', name: 'North Holland' },
        { code: 'OV', name: 'Overijssel' },
        { code: 'UT', name: 'Utrecht' },
        { code: 'ZE', name: 'Zeeland' },
        { code: 'ZH', name: 'South Holland' }
    ],
    '157': [ // New Zealand
        { code: 'AUK', name: 'Auckland' },
        { code: 'BOP', name: 'Bay of Plenty' },
        { code: 'CAN', name: 'Canterbury' },
        { code: 'GIS', name: 'Gisborne' },
        { code: 'HKB', name: 'Hawke\'s Bay' },
        { code: 'MWT', name: 'Manawatu-Wanganui' },
        { code: 'NTL', name: 'Northland' },
        { code: 'OTA', name: 'Otago' },
        { code: 'STL', name: 'Southland' },
        { code: 'TAS', name: 'Tasman' },
        { code: 'WKO', name: 'Waikato' },
        { code: 'WLG', name: 'Wellington' },
        { code: 'WTC', name: 'West Coast' }
    ],
    '158': [ // Nicaragua
        { code: 'BO', name: 'Boaco' },
        { code: 'CA', name: 'Carazo' },
        { code: 'CI', name: 'Chinandega' },
        { code: 'CO', name: 'Chontales' },
        { code: 'ES', name: 'Estelí' },
        { code: 'GR', name: 'Granada' },
        { code: 'JI', name: 'Jinotega' },
        { code: 'LE', name: 'León' },
        { code: 'MD', name: 'Madriz' },
        { code: 'MN', name: 'Managua' },
        { code: 'MS', name: 'Masaya' },
        { code: 'MT', name: 'Matagalpa' },
        { code: 'NS', name: 'Nueva Segovia' },
        { code: 'RI', name: 'Rivas' },
        { code: 'SJ', name: 'San Juan' }
    ],
    '333': [ // Nigeria
        { code: 'AB', name: 'Abia' },
        { code: 'AD', name: 'Adamawa' },
        { code: 'AK', name: 'Akwa Ibom' },
        { code: 'AN', name: 'Anambra' },
        { code: 'BA', name: 'Bauchi' },
        { code: 'BY', name: 'Bayelsa' },
        { code: 'BE', name: 'Benue' },
        { code: 'BO', name: 'Borno' },
        { code: 'CR', name: 'Cross River' },
        { code: 'DE', name: 'Delta' },
        { code: 'EB', name: 'Ebonyi' },
        { code: 'ED', name: 'Edo' },
        { code: 'EK', name: 'Ekiti' },
        { code: 'EN', name: 'Enugu' },
        { code: 'GO', name: 'Gombe' },
        { code: 'IM', name: 'Imo' },
        { code: 'JI', name: 'Jigawa' },
        { code: 'KD', name: 'Kaduna' },
        { code: 'KN', name: 'Kano' },
        { code: 'KT', name: 'Katsina' },
        { code: 'KE', name: 'Kebbi' },
        { code: 'KO', name: 'Kogi' },
        { code: 'KW', name: 'Kwara' },
        { code: 'LA', name: 'Lagos' },
        { code: 'NA', name: 'Nasarawa' },
        { code: 'NI', name: 'Niger' },
        { code: 'OG', name: 'Ogun' },
        { code: 'ON', name: 'Ondo' },
        { code: 'OS', name: 'Osun' },
        { code: 'OY', name: 'Oyo' },
        { code: 'PL', name: 'Plateau' },
        { code: 'RI', name: 'Rivers' },
        { code: 'SO', name: 'Sokoto' },
        { code: 'TA', name: 'Taraba' },
        { code: 'YO', name: 'Yobe' },
        { code: 'ZA', name: 'Zamfara' }
    ],
    '164': [ // Norway
        { code: '01', name: 'Akershus' },
        { code: '02', name: 'Aust-Agder' },
        { code: '03', name: 'Buskerud' },
        { code: '04', name: 'Finnmark' },
        { code: '05', name: 'Hedmark' },
        { code: '06', name: 'Hordaland' },
        { code: '07', name: 'Møre og Romsdal' },
        { code: '08', name: 'Nord-Trøndelag' },
        { code: '09', name: 'Nordland' },
        { code: '10', name: 'Oppland' },
        { code: '11', name: 'Oslo' },
        { code: '12', name: 'Rogaland' },
        { code: '13', name: 'Sogn og Fjordane' },
        { code: '14', name: 'Telemark' },
        { code: '15', name: 'Troms' },
        { code: '16', name: 'Vest-Agder' },
        { code: '17', name: 'Vestfold' },
        { code: '18', name: 'Østfold' }
    ],
    '169': [ // Panama
        { code: '01', name: 'Bocas del Toro' },
        { code: '02', name: 'Coclé' },
        { code: '03', name: 'Colón' },
        { code: '04', name: 'Chiriquí' },
        { code: '05', name: 'Darién' },
        { code: '06', name: 'Herrera' },
        { code: '07', name: 'Los Santos' },
        { code: '08', name: 'Panamá' },
        { code: '09', name: 'Veraguas' }
    ],
    '171': [ // Paraguay
        { code: '01', name: 'Asunción' },
        { code: '02', name: 'Alto Paraguay' },
        { code: '03', name: 'Alto Paraná' },
        { code: '04', name: 'Amambay' },
        { code: '05', name: 'Boquerón' },
        { code: '06', name: 'Caaguazú' },
        { code: '07', name: 'Caazapá' },
        { code: '08', name: 'Canindeyú' },
        { code: '09', name: 'Central' },
        { code: '10', name: 'Concepción' },
        { code: '11', name: 'Cordillera' },
        { code: '12', name: 'Guairá' },
        { code: '13', name: 'Itapúa' },
        { code: '14', name: 'Misiones' },
        { code: '15', name: 'Ñeembucú' },
        { code: '16', name: 'Paraguarí' },
        { code: '17', name: 'Presidente Hayes' },
        { code: '18', name: 'San Pedro' }
    ],
    '172': [ // Peru
        { code: 'AM', name: 'Amazonas' },
        { code: 'AN', name: 'Ancash' },
        { code: 'AP', name: 'Apurímac' },
        { code: 'AR', name: 'Arequipa' },
        { code: 'AY', name: 'Ayacucho' },
        { code: 'CJ', name: 'Cajamarca' },
        { code: 'CU', name: 'Cusco' },
        { code: 'HV', name: 'Huancavelica' },
        { code: 'HU', name: 'Huánuco' },
        { code: 'IC', name: 'Ica' },
        { code: 'JU', name: 'Junín' },
        { code: 'LL', name: 'La Libertad' },
        { code: 'LA', name: 'Lambayeque' },
        { code: 'LI', name: 'Lima' },
        { code: 'LO', name: 'Loreto' },
        { code: 'MO', name: 'Moquegua' },
        { code: 'PA', name: 'Pasco' },
        { code: 'PI', name: 'Piura' },
        { code: 'PU', name: 'Puno' },
        { code: 'SM', name: 'San Martín' },
        { code: 'TA', name: 'Tacna' },
        { code: 'TU', name: 'Tumbes' },
        { code: 'UC', name: 'Ucayali' }
    ],
    '353': [ // Philippines
        { code: 'ABR', name: 'Abra' },
        { code: 'AGN', name: 'Agusan del Norte' },
        { code: 'AGS', name: 'Agusan del Sur' },
        { code: 'AKL', name: 'Aklan' },
        { code: 'ALB', name: 'Albay' },
        { code: 'ANT', name: 'Antique' },
        { code: 'APA', name: 'Apayao' },
        { code: 'AUR', name: 'Aurora' },
        { code: 'BAS', name: 'Basilan' },
        { code: 'BAN', name: 'Bataan' },
        { code: 'BTN', name: 'Batanes' },
        { code: 'BTG', name: 'Batangas' },
        { code: 'BEN', name: 'Benguet' },
        { code: 'BIL', name: 'Biliran' },
        { code: 'BOH', name: 'Bohol' },
        { code: 'BUK', name: 'Bukidnon' },
        { code: 'BUL', name: 'Bulacan' },
        { code: 'CAG', name: 'Cagayan' },
        { code: 'CAN', name: 'Camarines Norte' },
        { code: 'CAS', name: 'Camarines Sur' },
        { code: 'CAM', name: 'Camiguin' },
        { code: 'CAP', name: 'Capiz' },
        { code: 'CAT', name: 'Catanduanes' },
        { code: 'CAV', name: 'Cavite' },
        { code: 'CEB', name: 'Cebu' },
        { code: 'COM', name: 'Compostela Valley' },
        { code: 'DAN', name: 'Davao del Norte' },
        { code: 'DAS', name: 'Davao del Sur' },
        { code: 'DAO', name: 'Davao Oriental' },
        { code: 'DIN', name: 'Dinagat Islands' },
        { code: 'EAS', name: 'Eastern Samar' },
        { code: 'GUI', name: 'Guimaras' },
        { code: 'IFU', name: 'Ifugao' },
        { code: 'ILI', name: 'Iloilo' },
        { code: 'ISA', name: 'Isabela' },
        { code: 'KAL', name: 'Kalinga' },
        { code: 'LUN', name: 'La Union' },
        { code: 'LAG', name: 'Laguna' },
        { code: 'LAN', name: 'Lanao del Norte' },
        { code: 'LAS', name: 'Lanao del Sur' },
        { code: 'LEY', name: 'Leyte' },
        { code: 'MAG', name: 'Maguindanao' },
        { code: 'MRN', name: 'Marinduque' },
        { code: 'MSR', name: 'Masbate' },
        { code: 'MDC', name: 'Mindoro Occidental' },
        { code: 'MDR', name: 'Mindoro Oriental' },
        { code: 'MSC', name: 'Misamis Occidental' },
        { code: 'MOR', name: 'Misamis Oriental' },
        { code: 'MOU', name: 'Mountain Province' },
        { code: 'NEC', name: 'Negros Occidental' },
        { code: 'NER', name: 'Negros Oriental' },
        { code: 'NSA', name: 'Northern Samar' },
        { code: 'NUE', name: 'Nueva Ecija' },
        { code: 'NUV', name: 'Nueva Vizcaya' },
        { code: 'PLW', name: 'Palawan' },
        { code: 'PAM', name: 'Pampanga' },
        { code: 'PAN', name: 'Pangasinan' },
        { code: 'QUE', name: 'Quezon' },
        { code: 'QUI', name: 'Quirino' },
        { code: 'RIZ', name: 'Rizal' },
        { code: 'ROM', name: 'Romblon' },
        { code: 'SAR', name: 'Sarangani' },
        { code: 'SCO', name: 'South Cotabato' },
        { code: 'SLE', name: 'Southern Leyte' },
        { code: 'SUK', name: 'Sultan Kudarat' },
        { code: 'SLU', name: 'Sulu' },
        { code: 'SUN', name: 'Surigao del Norte' },
        { code: 'SUR', name: 'Surigao del Sur' },
        { code: 'TAR', name: 'Tarlac' },
        { code: 'TAW', name: 'Tawi-Tawi' },
        { code: 'ZMB', name: 'Zambales' },
        { code: 'ZAN', name: 'Zamboanga del Norte' },
        { code: 'ZAS', name: 'Zamboanga del Sur' },
        { code: 'ZSI', name: 'Zamboanga Sibugay' }
    ],
    '175': [ // Poland
        { code: 'DS', name: 'Dolnośląskie' },
        { code: 'KP', name: 'Kujawsko-Pomorskie' },
        { code: 'LU', name: 'Lubelskie' },
        { code: 'LB', name: 'Lubuskie' },
        { code: 'LD', name: 'Łódzkie' },
        { code: 'MA', name: 'Małopolskie' },
        { code: 'MZ', name: 'Mazowieckie' },
        { code: 'OP', name: 'Opolskie' },
        { code: 'PK', name: 'Podkarpackie' },
        { code: 'PD', name: 'Podlaskie' },
        { code: 'PM', name: 'Pomorskie' },
        { code: 'SL', name: 'Śląskie' },
        { code: 'SK', name: 'Świętokrzyskie' },
        { code: 'WN', name: 'Warmińsko-Mazurskie' },
        { code: 'WP', name: 'Wielkopolskie' },
        { code: 'ZP', name: 'Zachodniopomorskie' }
    ],
    '176': [ // Portugal
        { code: '01', name: 'Aveiro' },
        { code: '02', name: 'Beja' },
        { code: '03', name: 'Braga' },
        { code: '04', name: 'Bragança' },
        { code: '05', name: 'Castelo Branco' },
        { code: '06', name: 'Coimbra' },
        { code: '07', name: 'Évora' },
        { code: '08', name: 'Faro' },
        { code: '09', name: 'Guarda' },
        { code: '10', name: 'Leiria' },
        { code: '11', name: 'Lisboa' },
        { code: '12', name: 'Portalegre' },
        { code: '13', name: 'Porto' },
        { code: '14', name: 'Santarém' },
        { code: '15', name: 'Setúbal' },
        { code: '16', name: 'Viana do Castelo' },
        { code: '17', name: 'Vila Real' },
        { code: '18', name: 'Viseu' },
        { code: '20', name: 'Madeira' },
        { code: '30', name: 'Açores' }
    ],
    '335': [ // Republic of Congo
        { code: '11', name: 'Bouenza' },
        { code: '15', name: 'Cuvette' },
        { code: '13', name: 'Kouilou' },
        { code: '12', name: 'Lékoumou' },
        { code: '05', name: 'Likouala' },
        { code: '02', name: 'Niari' },
        { code: '01', name: 'Plateaux' },
        { code: '14', name: 'Pointe-Noire' },
        { code: '09', name: 'Pool' },
        { code: '16', name: 'Sangha' }
    ],
    '336': [ // Democratic Republic of the Congo
        { code: 'BC', name: 'Bas-Congo' },
        { code: 'BN', name: 'Bandundu' },
        { code: 'EQ', name: 'Équateur' },
        { code: 'KA', name: 'Katanga' },
        { code: 'KE', name: 'Kasaï-Oriental' },
        { code: 'KN', name: 'Kinshasa' },
        { code: 'MA', name: 'Maniema' },
        { code: 'NK', name: 'Nord-Kivu' },
        { code: 'OR', name: 'Orientale' },
        { code: 'SK', name: 'Sud-Kivu' }
    ],
    '61': [ // Dominican Republic
        { code: '01', name: 'Distrito Nacional' },
        { code: '02', name: 'Azua' },
        { code: '03', name: 'Baoruco' },
        { code: '04', name: 'Barahona' },
        { code: '05', name: 'Dajabón' },
        { code: '06', name: 'Duarte' },
        { code: '07', name: 'Elías Piña' },
        { code: '08', name: 'El Seibo' },
        { code: '09', name: 'Espaillat' },
        { code: '10', name: 'Independencia' },
        { code: '11', name: 'La Altagracia' },
        { code: '12', name: 'La Romana' },
        { code: '13', name: 'La Vega' },
        { code: '14', name: 'María Trinidad Sánchez' },
        { code: '15', name: 'Monte Cristi' },
        { code: '16', name: 'Pedernales' },
        { code: '17', name: 'Peravia' },
        { code: '18', name: 'Puerto Plata' },
        { code: '19', name: 'Hermanas Mirabal' },
        { code: '20', name: 'Samaná' },
        { code: '21', name: 'San Cristóbal' },
        { code: '22', name: 'San José de Ocoa' },
        { code: '23', name: 'San Juan' },
        { code: '24', name: 'San Pedro de Macorís' },
        { code: '25', name: 'Santiago' },
        { code: '26', name: 'Santiago Rodríguez' },
        { code: '27', name: 'Santo Domingo' },
        { code: '28', name: 'Valverde' }
    ],
    '334': [ // Rwanda
        { code: '01', name: 'Kigali' },
        { code: '02', name: 'Eastern' },
        { code: '03', name: 'Northern' },
        { code: '04', name: 'Western' },
        { code: '05', name: 'Southern' }
    ],
    '180': [ // Romania
        { code: 'AB', name: 'Alba' },
        { code: 'AR', name: 'Arad' },
        { code: 'AG', name: 'Argeș' },
        { code: 'BC', name: 'Bacău' },
        { code: 'BH', name: 'Bihor' },
        { code: 'BN', name: 'Bistrița-Năsăud' },
        { code: 'BR', name: 'Brăila' },
        { code: 'BT', name: 'Botoșani' },
        { code: 'BV', name: 'Brașov' },
        { code: 'BZ', name: 'Buzău' },
        { code: 'CS', name: 'Caraș-Severin' },
        { code: 'CL', name: 'Călărași' },
        { code: 'CJ', name: 'Cluj' },
        { code: 'CT', name: 'Constanța' },
        { code: 'CV', name: 'Covasna' },
        { code: 'DB', name: 'Dâmbovița' },
        { code: 'DJ', name: 'Dolj' },
        { code: 'GL', name: 'Galați' },
        { code: 'GR', name: 'Giurgiu' },
        { code: 'GJ', name: 'Gorj' },
        { code: 'HR', name: 'Harghita' },
        { code: 'HD', name: 'Hunedoara' },
        { code: 'IL', name: 'Ialomița' },
        { code: 'IS', name: 'Iași' },
        { code: 'IF', name: 'Ilfov' },
        { code: 'MM', name: 'Maramureș' },
        { code: 'MH', name: 'Mehedinți' },
        { code: 'MS', name: 'Mureș' },
        { code: 'NT', name: 'Neamț' },
        { code: 'OT', name: 'Olt' },
        { code: 'PH', name: 'Prahova' },
        { code: 'SJ', name: 'Sălaj' },
        { code: 'SM', name: 'Satu Mare' },
        { code: 'SB', name: 'Sibiu' },
        { code: 'SV', name: 'Suceava' },
        { code: 'TR', name: 'Teleorman' },
        { code: 'TM', name: 'Timiș' },
        { code: 'TL', name: 'Tulcea' },
        { code: 'VS', name: 'Vaslui' },
        { code: 'VL', name: 'Vâlcea' },
        { code: 'VN', name: 'Vrancea' },
        { code: 'B', name: 'Bucharest' }
    ],
    '181': [ // Russia
        { code: 'AD', name: 'Adygea' },
        { code: 'AL', name: 'Altai Republic' },
        { code: 'BA', name: 'Bashkortostan' },
        { code: 'BU', name: 'Buryatia' },
        { code: 'CE', name: 'Chechnya' },
        { code: 'CU', name: 'Chuvashia' },
        { code: 'DA', name: 'Dagestan' },
        { code: 'IN', name: 'Ingushetia' },
        { code: 'KB', name: 'Kabardino-Balkaria' },
        { code: 'KL', name: 'Kalmykia' },
        { code: 'KC', name: 'Karachay-Cherkessia' },
        { code: 'KR', name: 'Karelia' },
        { code: 'KO', name: 'Komi' },
        { code: 'ME', name: 'Mari El' },
        { code: 'MO', name: 'Mordovia' },
        { code: 'SA', name: 'Sakha (Yakutia)' },
        { code: 'SE', name: 'North Ossetia-Alania' },
        { code: 'TA', name: 'Tatarstan' },
        { code: 'TY', name: 'Tuva' },
        { code: 'UD', name: 'Udmurtia' }
    ],

    '187': [ // Saint Vincent & the Grenadines
        { code: '01', name: 'Charlotte' },
        { code: '02', name: 'Grenadines' },
        { code: '03', name: 'Saint Andrew' },
        { code: '04', name: 'Saint David' },
        { code: '05', name: 'Saint George' },
        { code: '06', name: 'Saint Patrick' }
    ],
    '185': [ // Saint Lucia
        { code: '01', name: 'Anse la Raye' },
        { code: '02', name: 'Castries' },
        { code: '03', name: 'Choiseul' },
        { code: '04', name: 'Dennery' },
        { code: '05', name: 'Gros Islet' },
        { code: '06', name: 'Laborie' },
        { code: '07', name: 'Micoud' },
        { code: '08', name: 'Soufrière' },
        { code: '09', name: 'Vieux Fort' }
    ],
    '184': [ // Saint Kitts & Nevis
        { code: '01', name: 'Christ Church Nichola Town' },
        { code: '02', name: 'Saint Anne Sandy Point' },
        { code: '03', name: 'Saint George Basseterre' },
        { code: '04', name: 'Saint George Gingerland' },
        { code: '05', name: 'Saint James Windward' },
        { code: '06', name: 'Saint John Capisterre' },
        { code: '07', name: 'Saint John Figtree' },
        { code: '08', name: 'Saint Mary Cayon' },
        { code: '09', name: 'Saint Paul Capisterre' },
        { code: '10', name: 'Saint Paul Charlestown' },
        { code: '11', name: 'Saint Peter Basseterre' },
        { code: '12', name: 'Saint Thomas Lowland' },
        { code: '13', name: 'Saint Thomas Middle Island' },
        { code: '15', name: 'Trinity Palmetto Point' }
    ],
    '189': [ // San Marino
        { code: '01', name: 'Acquaviva' },
        { code: '02', name: 'Borgo Maggiore' },
        { code: '03', name: 'Chiesanuova' },
        { code: '04', name: 'Domagnano' },
        { code: '05', name: 'Faetano' },
        { code: '06', name: 'Fiorentino' },
        { code: '07', name: 'Montegiardino' },
        { code: '08', name: 'San Marino Città' },
        { code: '09', name: 'Serravalle' }
    ],
    '186': [], // Saint Pierre et Miquelon (no sub-divisions)
    '337': [], // Santo Tome y Principe (no sub-divisions)
    '338': [ // Senegal
        { code: 'DK', name: 'Dakar' },
        { code: 'DB', name: 'Diourbel' },
        { code: 'FK', name: 'Fatick' },
        { code: 'KA', name: 'Kaffrine' },
        { code: 'KL', name: 'Kaolack' },
        { code: 'KD', name: 'Kédougou' },
        { code: 'KE', name: 'Kolda' },
        { code: 'LG', name: 'Louga' },
        { code: 'MT', name: 'Matam' },
        { code: 'SL', name: 'Saint-Louis' },
        { code: 'SE', name: 'Sédhiou' },
        { code: 'TC', name: 'Tambacounda' },
        { code: 'TH', name: 'Thiès' },
        { code: 'ZG', name: 'Ziguinchor' }
    ],
    '193': [ // Serbia
        { code: '00', name: 'Belgrade' },
        { code: '01', name: 'Vojvodina' },
        { code: '02', name: 'Šumadija and Western Serbia' },
        { code: '03', name: 'Southern and Eastern Serbia' },
        { code: '04', name: 'Kosovo and Metohija' }
    ],
    '339': [], // Seychelles (no sub-divisions)
    '340': [ // Sierra Leone
        { code: 'E', name: 'Eastern' },
        { code: 'N', name: 'Northern' },
        { code: 'S', name: 'Southern' },
        { code: 'W', name: 'Western Area' }
    ],
    '197': [ // Slovakia
        { code: '01', name: 'Bratislava' },
        { code: '02', name: 'Trnava' },
        { code: '03', name: 'Trenčín' },
        { code: '04', name: 'Nitra' },
        { code: '05', name: 'Žilina' },
        { code: '06', name: 'Banská Bystrica' },
        { code: '07', name: 'Prešov' },
        { code: '08', name: 'Košice' }
    ],
    '198': [ // Slovenia
        { code: '001', name: 'Ajdovščina' },
        { code: '002', name: 'Beltinci' },
        // Add more regions as required...
    ],
    '341': [], // Somalia (no sub-divisions)
    '202': [ // South Africa
        { code: 'EC', name: 'Eastern Cape' },
        { code: 'FS', name: 'Free State' },
        { code: 'GP', name: 'Gauteng' },
        { code: 'KZN', name: 'KwaZulu-Natal' },
        { code: 'LP', name: 'Limpopo' },
        { code: 'MP', name: 'Mpumalanga' },
        { code: 'NC', name: 'Northern Cape' },
        { code: 'NW', name: 'North West' },
        { code: 'WC', name: 'Western Cape' }
    ],
    '344': [], // Swaziland (Eswatini) (no sub-divisions)
    '342': [ // Sudan
        { code: 'RS', name: 'Red Sea' },
        { code: 'KS', name: 'Khartoum' },
        { code: 'NR', name: 'Northern' },
        // Add more states as needed...
    ],
    '343': [ // South Sudan
        { code: 'BW', name: 'Central Equatoria' },
        { code: 'EE', name: 'Eastern Equatoria' },
        // Add more states...
    ],
    '208': [], // Suriname (no sub-divisions)
    '211': [ // Sweden
        { code: 'AB', name: 'Stockholm' },
        { code: 'AC', name: 'Västerbotten' },
        // Add more provinces as required...
    ],
    '212': [ // Switzerland
        { code: 'AG', name: 'Aargau' },
        { code: 'AI', name: 'Appenzell Innerrhoden' },
        { code: 'AR', name: 'Appenzell Ausserrhoden' },
        // Add more cantons...
    ],
    '351': [], // Syria (no sub-divisions)
    '345': [ // Tanzania
        { code: '01', name: 'Arusha' },
        { code: '02', name: 'Dar es Salaam' },
        // Add more regions...
    ],
    '346': [ // Togo
        { code: 'C', name: 'Centrale' },
        { code: 'K', name: 'Kara' },
        { code: 'M', name: 'Maritime' },
        { code: 'P', name: 'Plateaux' },
        { code: 'S', name: 'Savanes' }
    ],
    '221': [], // Trinidad & Tobago (no sub-divisions)
    '222': [ // Tunisia
        { code: '11', name: 'Tunis' },
        { code: '12', name: 'Ariana' },
        // Add more regions...
    ],
    '223': [ // Turkey
        { code: '01', name: 'Adana' },
        { code: '02', name: 'Adıyaman' },
        // Add more provinces...
    ],
    '225': [], // Turks & Caicos Islands (no sub-divisions)
    '347': [], // Uganda (no sub-divisions)
    '228': [ // Ukraine
        { code: '05', name: 'Cherkasy' },
        { code: '07', name: 'Chernihiv' },
        // Add more oblasts...
    ],
    '301': [ // United Arab Emirates
        { code: 'AZ', name: 'Abu Dhabi' },
        { code: 'SH', name: 'Sharjah' },
        { code: 'DXB', name: 'Dubai' },
        { code: 'AJ', name: 'Ajman' },
        { code: 'FU', name: 'Fujairah' },
        { code: 'RAK', name: 'Ras Al Khaimah' },
        { code: 'UAQ', name: 'Umm Al-Quwain' },
        { code: 'AD', name: 'Abu Dhabi' },
        { code: 'D', name: 'Dubai' },
        { code: 'SH', name: 'Sharjah' },
        { code: 'A', name: 'Ajman' },
        { code: 'F', name: 'Fujairah' },
        { code: 'R', name: 'Ras Al Khaimah' },
        { code: 'U', name: 'Umm Al-Quwain' }
    ],
    '230': [ // United Kingdom
        { code: 'ENG', name: 'England' },
        { code: 'SCT', name: 'Scotland' },
        { code: 'WLS', name: 'Wales' },
        { code: 'NIR', name: 'Northern Ireland' },
        { code: 'GB', name: 'Great Britain' },
        { code: 'UK', name: 'United Kingdom' }
    ],
    '233': [], // Uruguay (no sub-divisions)
    '231': [ // USA
        { code: 'AL', name: 'Alabama' },
        { code: 'AK', name: 'Alaska' },
        { code: 'AZ', name: 'Arizona' },
        { code: 'AR', name: 'Arkansas' },
        { code: 'CA', name: 'California' },
        { code: 'CO', name: 'Colorado' },
        { code: 'CT', name: 'Connecticut' },
        { code: 'DE', name: 'Delaware' },
        { code: 'FL', name: 'Florida' },
        { code: 'GA', name: 'Georgia' },
        { code: 'HI', name: 'Hawaii' },
        { code: 'ID', name: 'Idaho' },
        { code: 'IL', name: 'Illinois' },
        { code: 'IN', name: 'Indiana' },
        { code: 'IA', name: 'Iowa' },
        { code: 'KS', name: 'Kansas' },
        { code: 'KY', name: 'Kentucky' },
        { code: 'LA', name: 'Louisiana' },
        { code: 'ME', name: 'Maine' },
        { code: 'MD', name: 'Maryland' },
        { code: 'MA', name: 'Massachusetts' },
        { code: 'MI', name: 'Michigan' },
        { code: 'MN', name: 'Minnesota' },
        { code: 'MS', name: 'Mississippi' },
        { code: 'MO', name: 'Missouri' },
        { code: 'MT', name: 'Montana' },
        { code: 'NE', name: 'Nebraska' },
        { code: 'NV', name: 'Nevada' },
        { code: 'NH', name: 'New Hampshire' },
        { code: 'NJ', name: 'New Jersey' },
        { code: 'NM', name: 'New Mexico' },
        { code: 'NY', name: 'New York' },
        { code: 'NC', name: 'North Carolina' },
        { code: 'ND', name: 'North Dakota' },
        { code: 'OH', name: 'Ohio' },
        { code: 'OK', name: 'Oklahoma' },
        { code: 'OR', name: 'Oregon' },
        { code: 'PA', name: 'Pennsylvania' },
        { code: 'RI', name: 'Rhode Island' },
        { code: 'SC', name: 'South Carolina' },
        { code: 'SD', name: 'South Dakota' },
        { code: 'TN', name: 'Tennessee' },
        { code: 'TX', name: 'Texas' },
        { code: 'UT', name: 'Utah' },
        { code: 'VT', name: 'Vermont' },
        { code: 'VA', name: 'Virginia' },
        { code: 'WA', name: 'Washington' },
        { code: 'WV', name: 'West Virginia' },
        { code: 'WI', name: 'Wisconsin' },
        { code: 'WY', name: 'Wyoming' }
    ],
    
            // Add states for other countries...
        };

        return statesData[countryCode] || [];
    }
</script>

<script>
    // document.getElementById('geo_area_change').addEventListener('change', function() {
    //     const value = this.value;

    //     // Close any open modals first
    //     $('#nationalModal').modal('hide');
    //     $('#stateModal').modal('hide');

    //     // Open the appropriate modal based on the selection
    //     if (value === '1') {
    //         $('#nationalModal').modal('show');
    //     } else if (value === '2') {
    //         $('#stateModal').modal('show');
    //     }
    // });
</script>